mozilla/cubeb

src/cubeb_audiounit.c
I see the following clang warnings when compiling cubeb as part of Firefox:
```
media/libcubeb/src/cubeb_audiounit.c:480:17: warning: unused variable 'output_device_id' [-Wunused-variable]
media/libcubeb/src/cubeb_audiounit.c:786:17: warning: unused variable 'id' [-Wunused-variable]
```
=> Fix -Wunused-variable warnings

src/cubeb_audiounit.c
I found that running test/test_audio would crash running on OS X with audiounit backend due to the fact that stereo panning is done on float samples only.
Running under valgrind:
```
Testing: volume
Volume: 0%
Volume: 25%
Volume: 50%
Volume: 75%
Volume: 100%
Testing: panning
Panning: -1.00%
==27784== Thread 7 com.apple.audio.IOThread.client:
==27784== Invalid read of size 4
==27784==    at 0x100018D10: cubeb_pan_stereo_buffer_float (in /$SRCDIR/cubeb/src/.libs/libcubeb.0.dylib)
==27784==    by 0x10001A013: audiounit_output_callback (in /$SRCDIR/cubeb/src/.libs/libcubeb.0.dylib)
==27784==    by 0x10916E73A: AUInputElement::PullInput(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int) (in /System/Library/Components/CoreAudio.component/Contents/MacOS/CoreAudio)
==27784==    by …
```
=> audiounit: Support both signed 16bit and float stereo panning.

m4/ax_create_stdint_h.m4
Caused ./configure to fail running mintty/zsh from MSYS2
=> m4: Split "fi fi" to single lines.

src/cubeb.c
Some systems have a PulseAudio server running above JACK. This patch ensure that JACK will be preferably used on systems where both APIs are available. On JACK-less systems, it should have no effect.
=> Try to connect to JACK before PulseAudio.

include/cubeb/cubeb.h, src/cubeb-internal.h, src/cubeb.c, src/cubeb_alsa.c, src/cubeb_audiotrack.c, src/cubeb_audiounit.c, src/cubeb_opensl.c, src/cubeb_pulse.c, src/cubeb_resampler.cpp, src/cubeb_resampler.h, src/cubeb_sndio.c, src/cubeb_wasapi.cpp, src/cubeb_winmm.c, test/test_audio.cpp, test/test_sanity.cpp, test/test_tone.cpp
This is changing all the signatures of the `cubeb_stream_init` implementations,
the signature of the `data_callback` type, so that cubeb can support audio
input.
`cubeb_stream_init` now has two `cubeb_stream_params` pointers, one for input,
one for output. If two pointers are passed, a "duplex" stream is opened. If only
one pointer is passed, an input-only or output-only stream is created.
Duplex streams have the same sample rate, and sample type. They don't have to
have the same number of channels.
`data_callback` now has two pointers to audio buffers: an input buffer (`NULL`
if this is an output-only stream) containing input data (e.g. a microphone), and
an output buffer, to be filled, as usual, with the audio frames to play. The
two buffers always have the exact same number of audio …
=> Preparatory work for the input and duplex code

include/cubeb/cubeb.h, src/cubeb-internal.h, src/cubeb.c, src/cubeb_alsa.c, src/cubeb_audiotrack.c, src/cubeb_audiounit.c, src/cubeb_opensl.c, src/cubeb_pulse.c, src/cubeb_sndio.c, src/cubeb_wasapi.cpp, src/cubeb_winmm.c, test/test_audio.cpp, test/test_sanity.cpp, test/test_tone.cpp
Change on the signature of cubeb_stream_init to add the device input/output that will be connected. If NULL provided the default device should be chosen. 
Change on the signature for data_callback to make the input buffer const since it is not safe for some implementations to treat the buffer as non-const.
=> Signature changes for stream init and data callback

src/cubeb_pulse.c
Alex's patch.  Comment from Ford_Prefect in IRC:
[20:42]	Ford_Prefect	achronop: your patch is actually correct (setting the data callback to NULL)
[20:43]	Ford_Prefect	achronop: padenot: jesup: basically you're setting disconnecting the stream (which is async) and then free'ing stm -- any pending data callbacks will still come through when you unlock the threaded mainloop there, which is what could cause that problem
[20:45]	Ford_Prefect	achronop: padenot: jesup: so either you wait till you see the stream state change to PA_STREAM_TERMINATED before freeing things, or disconnect all callbacks
[20:46]	Ford_Prefect	s/setting// in the previous line
@padenot @achronop
=> Clear callbacks before disconnecting pulse streams

src/cubeb_pulse.c
=> pulse: Drop now-redundant assert in stream read callback

src/cubeb_opensl.c
Android/arm64 doesn't export __system_property_get on NDK.  So we shouldn't this API to get API level on 64bit Android, and, API level is already 10+, it is unnecessary to check whether JB MR1.
=> Unnecessary to check Android version if android api level > 10

src/cubeb_resampler.cpp, src/cubeb_resampler_internal.h, test/test_resampler.cpp
The PR solves link error on build of test_resampler on MAC. It also adds a few spaces for pretty printing in test_resampler. The errors has been found during the testing of audiounit full-duplex implementation.
=> Fix link error on test_resampler build.

.gitignore, Makefile.am, include/cubeb/cubeb.h, src/cubeb.c, src/cubeb_audiounit.c, src/cubeb_pulse.c, src/cubeb_resampler.cpp, src/cubeb_resampler_internal.h, src/cubeb_ring_array.h, test/test_resampler.cpp, test/test_ring_array.c
The PR implements the full-duplex functionality for audiounit. The idea is to configure two different audiounit (AU) one for the input and one for the output. The input AU operates in device sampling rate thus the new full-duplex cubeb_resampler is used to modify the input when necessary. Output AU operates correctly in the user selected sampling rate.
In addtion AU operates on different threads. Thread sequence is not guaranteed thus a primitive ring array was implemented to hold the incoming buffers and feed them to the output in the right order. For this reason a new header file is added with the corresponding test file.
Last thing to note is that the newly added devid data member of cubeb_device_info struct set to free inside the general method cubeb_device_info_destroy(). This is …
=> Implement full-duplex for audiounit backend.

src/cubeb_audiounit.c
This PR is the implementation of device change notifications. The idea is that every time a device is plugged or unplugged the corresponding callback will be called.
One thing to note in the implementation is that Apple framework does not differentiate if the device is input or output device. I worked around this by keeping the number of devices in the desired type and compering with the new updated number. A second thing to note is that the current implementation does not accept multiply register of the notify callback without deregister the previous one. If that is not acceptable please let me know.
Thanks!
=> Audiounit device change notifications

src/cubeb_resampler.cpp, src/cubeb_resampler_internal.h, src/cubeb_utils.h, test/test_resampler.cpp
I had to rework the draining sequence a bit to make it more like it was, and I found an horrible bug in the setup of the output resampler. I need to investigate why it was not caught by the test, and write more tests so that it can't happen again. I'll push a commit or two to do that tomorrow.
=> Fix more resampler issues

src/cubeb_audiounit.c
Handle the case that audio device of the same type coalescing. The general idea is that devids are stored in arrays which are compared when the number of devices before and after change is the same. Also added to unregister callback in cubeb_destroy if necessary.  
PR is addressing issue #85
=> audiounit: Handle device change callback coalescing

src/cubeb_resampler_internal.h, src/cubeb_utils.h
Clear a build error found during the Static Checking Build of OS X 10.7
=> Declare constructor of processor and auto_array explicit

test/test_resampler.cpp
The failure was caused by switching from `abs()` to `fabs()`. This partially fix the test, and disables it for reasons explained in #93.
=> Fix and disable a test

test/test_duplex.cpp, test/test_record.cpp
Change the version of _XOPEN_SOURCE used from 5 to 6. Version 5 caused compilation error in gecko. Also correct the xpcom scoped name of test_duplex.
=> Correct gecko macros

src/cubeb_wasapi.cpp
Somehow we missed this. I don't know yet how to write tests for this, I'm investigating kernel modules to insert in the machine during tests, but I haven't found a nice solution yet.
=> Use the device ID to choose the device in cubeb_wasapi.cpp.

src/cubeb_audiounit.c
Register the listener for default input device. Also it check if input, output or both is activated in order to register for the corresponding default devices.
=> Input device change callback

src/cubeb.c, src/cubeb_audiounit.c
Top level function does not allow to set NULL cb method. This is useful to deregister the cb. 
Nit: Also includes one small format change.
PS. This patch is not required to be imported directly to Gecko since the latter does not use this capability and the current state of the code does not need it.
=> Allow NULL callback for deregister

src/cubeb_audiounit.c
Use old enums to keep backward compatibility with 10.7.
=> Use old enums for backward compatibility.

src/cubeb_resampler_internal.h
Change the formula used in computation of output frames for a given input.
=> Resampler: correct output for input frames calculation

src/cubeb_resampler.cpp
Two small fixes for resampler found during opensl es testing. 
1. The out only or full-duplex flavors of fill method cannot return negative values of user callback. Instead of that they use the negative numbers as input arguments to unassigned values which cause overflow. Change: returns immediately when receive negative values from user callback.
2. The input only fill method is used with requested frames == 0. It's return value is the after resampling number of frames. But this number is not available on the resampler's client. The return number is used to examine for drain or error cases. Change: return the similar percentage of the processed frames transformed into initial number of input frame.
=> Resampler fixes

src/cubeb_wasapi.cpp
In Gecko, `webrtc.org` code we call from the callback is using big arrays
allocated on the stack, and we're running out of stack space. Bumping it by a
factor of two should be enough.
=> Bump the stack size for WASAPI rendering threads.

src/cubeb_resampler_internal.h
Change the way that in or out frames needed are calculated. Since there is no m-c bug about it I copy here the try run of the fix.
https://treeherder.mozilla.org/#/jobs?repo=try&revision=6c1d253ab037
=> resampler: change calculation for in/out frames needed

src/cubeb_wasapi.cpp
It's legal to call `cubeb_stream_stop` twice in a row.
=> Remove an assert in the WASAPI backend

include/cubeb/cubeb.h, src/cubeb.c, src/cubeb_alsa.c, src/cubeb_audiotrack.c, src/cubeb_audiounit.cpp, src/cubeb_jack.cpp, src/cubeb_kai.c, src/cubeb_opensl.c, src/cubeb_pulse.c, src/cubeb_sndio.c, src/cubeb_wasapi.cpp, src/cubeb_winmm.c, test/test_devices.c, test/test_duplex.cpp, test/test_latency.cpp, test/test_sanity.cpp
We need to have a tight control over the latency numbers to trigger fast paths and such.
=> Latency numbers should be in frames

src/cubeb_audiounit.cpp, test/test_audio.cpp
OSX allows to go lower, but a number of headsets and other hw don't work too
well with super low latency.
=> Clamp the latency to [256, platform default] on OSX.

.travis.yml, src/cubeb_audiounit.cpp
This fixes a thing in the OSX backend so it builds fine on Travis, changes a bit the .travis.yml, and disables the test on OSX.
Only five of them pass currently, and I don't know how to disable only a few test using autoconf and automake and all.
@kinetiknz, does that look reasonable?
=> Add travis support for OSX

src/cubeb_utils_unix.h
This is to update the cubeb repo with a change made directly to m-c. `owned_critical_section` is not intend to be recursive. OSX implementation is not ready for non-recursive stream mutex. The change made directly in m-c in order to fix the broken nightly behavior. A bug will be opened to address all changes required in order to restore the non-recursing behavior.
=> Missing update from gecko

src/cubeb_audiounit.cpp, src/cubeb_utils_unix.h
The `recursive` attribute has been replaced with `normal` in release or `errorcheck` in debug. The critical memory that caused the deadlock, data member `cubeb_stream::panning`, has been turned into atomic in order to ensure synchronization. Patch fixes issue #144 .
=> Restore non-recursive behavior of mutex wrapper

src/cubeb_audiounit.cpp
6b2c610e changed the output unit from kAudioUnitSubType_DefaultOutput to
kAudioUnitSubType_HALOutput because capture is never available on the
DefaultOutputUnit.  For the case where we're doing output only to the default
device, this regressed the automatic device switching when the output device
was changed in the Sound system preferences.  Reverting to the
DefaultOutputUnit for this case restores the previous behaviour.  This
addresses BMO #1278612.
=> audiounit: Use DefaultOutputUnit as the default output device.

src/cubeb_winmm.c
Two changes to address BMO# 1274479.
- Change the WinMM backend's context initialization to require a device so that we don't permanently fall back to WinMM when no device is available when attempting to initialize the WASAPI backend.
- Try to detect that the waveout device has been lost in winmm_stream_destroy so we can avoid waiting indefinitely on buffers to become free from a non-existent device.
=> winmm: Fix bad fallback behaviour and shutdown hang with lost devices

src/cubeb_resampler.cpp, src/cubeb_resampler_internal.h, src/cubeb_wasapi.cpp
(Re-opening a PR since I'm apparently hitting a race on github)
This addresses the comments, and is cleaner. I removed the explicit buffer append at start, in favour of letting the emergency padding logic automatically kick in. Usually, we never append input frames, it's mainly useful when we're intentionally blocking thread because we're hitting breakpoints, or at start when the input side has not produced enough buffers yet to feed the resampler.
=> Fix drift in WASAPI when having different output and input sample device rate

src/cubeb_wasapi.cpp
=> Handle not having input frames in refill_callback_input.

src/cubeb_wasapi.cpp
We downmix right before, so this is in frames in with the channel count of the
stream, not the mix.
=> Divide by the number of channel of the stream to compute the duration of the buffer

include/cubeb/cubeb.h, src/cubeb_log.h, src/cubeb_pulse.c, src/cubeb_wasapi.cpp
The new LOG*() macros are too complicated for my liking, which I glossed over in my initial review:
- the stdout/stderr casting is extremely hacky and can be easily achieved in the caller-supplied log callback
- introducing variables in the LOG*() macros causes naming clashes in real code (c.f. ec775436921bbe2eb200aac89fafc2284c81ca7f for the first example)
- the macros should be as simple as possible since they're effectively inlined everywhere
There were also a bunch of places where LOG*() was being supplied with a newline, which is now fixed.
=> Simplify logging macro and clean up a bit

src/cubeb_alsa.c, src/cubeb_pulse.c, test/test_devices.c
This casts them to `void`, so it's quite portable, but we can also use a macro that expands to the compiler-specific annotation if we prefer.
@kinetiknz, can you have a look ?
=> Fix unused parameter warning

src/cubeb_audiounit.cpp
This is what webrtc.org used to do, and we feel it's better.
@achronop, can you have a look ?
=> Use the data source name if available on OSX. If not, use the device name

src/cubeb_resampler_internal.h
It helps on some configuration (Plantronics 648 headset + internal mic, rounding
instead of ceiling would make an rounding error not accumulate), but break
others (Creative X-Fi Titanium Fatal1ty Pro and some Android phones), so I want
to revert this and try another fix.
=> Revert part of 6ae23a635.

src/cubeb_audiounit.cpp
=> Fix unused parameter/variable warnings in cubeb_audiounit.cpp

src/cubeb.c, src/cubeb_audiounit.cpp, src/cubeb_wasapi.cpp
We need to be able to ask people to enable logging and have a lot of info from machines we don't control, so I added a bunch of logging statements. Sometimes, the logging statement is only there to see where the program errored.
This includes logging about device enumeration, that I copied and adapted from `test_device.c`.
@kinetiknz, @achronop, can you have a look ?
=> Improve logging

test/test_sanity.cpp
This would have caught the OpenSLES issues when merging into gecko I believe
=> Add a test that makes sure the clock value is not reset by starting/stopping the stream

src/cubeb_audiounit.cpp
The deallocation is handled via free() in cubeb_device_info_destroy in cubeb.c
and the allocator and deallocator *must* match.
=> audiounit: Revert bad allocation change made in c4dc6e02

src/cubeb_wasapi.cpp
cubeb_device_info member deallocation is handled via free() in
cubeb_device_info_destroy in cubeb.c but was being allocated with new[]
in wstr_to_utf8.
std::unique_ptr<wchar_t *> uses a different deallocator to
std::unique_ptr<wchar_t []>, resulting in an allocator mismatch.
r? @padenot
=> wasapi: Revert bad allocation changes made in 6f13113.

src/cubeb_wasapi.cpp
Simple fix suitable for uplift.
I'm working on fixing this permanently by switching to smart COM pointers, branch coming soon.
r? @padenot
=> wasapi: Fix leak of stm->capture_client in close_wasapi_stream.

src/cubeb_audiounit.cpp
The branch contains an number of fixes found using the Logitech c920 and c930 webcam.
- Bug1306247: Do not crash when camera is unplugged.
- Bug1272386: Do not assert on debug when c930 starts.
- Bug1311911: Build up latency with c920.
- Switch to default device when camera is unplugged or when a different default device is chosen from audio settings.
- Add some useful debug logs.
- Correct small errors.
About device switching behavior a discussion is on going on #167. The device switching behavior implemented here is not the final but a good compromise till we reach to a conclusion.
=> audiounit: Crash and device switch fixes

include/cubeb/cubeb.h, src/cubeb.c, src/cubeb_wasapi.cpp
Make API visible cubeb_device_info members and cubeb_devid const.
The API user is never permitted to modify these (nor deallocate them
directly, which non-const can imply), so they should marked const in the
public definition.
I suspect this happened originally because free()ing the
cubeb_device_info members requires casting const away in
cubeb_device_info_destroy, but other than being slightly ugly there's no
problem doing that and it's better to have the public API be consistent.
This also allows fixing the const-ness of utf8_to_wstr and wstr_to_utf8
const in cubeb_wasapi.cpp.
r? @padenot
=>  Make API visible cubeb_device_info members and cubeb_devid const.

src/cubeb_audiounit.cpp, src/cubeb_jack.cpp, src/cubeb_pulse.c, src/cubeb_wasapi.cpp, src/cubeb_winmm.c
cubeb_devid is intended to be an opaque type for API users.  Internally,
a cubeb_devid should be converted to the original type at the earliest
possible point.
It's difficult to get the types right on all platforms, since some of the internal types for cubeb_devid have implicit conversion to and from void*.  A useful compile test is to change the definition of cubeb_devid from void* to uintptr_t and rebuild, fixing whatever breaks.
It'd be nice if cubeb_devid was always defined as uintptr_t, but that loses the nice API property that allows passing a NULL pointer for the default device.
Note, this is based on the constify_api branch, so must be merged in the correct order.
=> Avoid using cubeb_devid internally.

src/cubeb_resampler_internal.h
In practice, depending on the resampling direction (input or output), either `resampling_in_buffer` is empty or `resampling_out_buffer` is empty.
=> Prevent underflowing the number of input frames needed in input when resampling

src/cubeb_wasapi.cpp
This is over-complicated because we don't have `atomic_shared_ptr` in standard C++ for now, and because I don't want this to be non-atomic, and I don't want to add a global lock or another mutex.
=> Bail out safely from the rendering loop if we could not join the rendering thread in time

src/cubeb_pulse.c
When starting a stream, trigger_user_callback may be called from
stream_write_callback and immediately enter a drain situation, creating
a drain timer and setting shutdown to true.  If pulse_defer_event_cb
then runs without checking for shutdown, it can overwrite the current
timer with a new timer, resulting in a leaked timer and a null pointer
assertion.
=> pulse: Bail early from pulse_defer_event_cb when shutting down.

src/cubeb_audiounit.cpp, test/test_sanity.cpp
ddbc367 removed the holding of stm->mutex from the render callback and switched some fields to std::atomic, but frames_played was missed.
Also includes some TSAN fixes for test_sanity.
=> audiounit: Fix race on frames_played.

CMakeLists.txt, src/cubeb_utils.h, src/cubeb_utils_unix.h, src/cubeb_utils_win.h, src/cubeb_wasapi.cpp
This converts the WASAPI backend to using smart pointers where possible.  I wrote a small com_ptr since the standard Microsoft version requires building with ATL, which we (and Gecko) want to avoid.
There's plenty more we can do (e.g. avoid double-initializating cubeb_stream by passing the params into a constructor), but I've tried to make each of these changes minimal to make review easier.
r? @padenot
=> wasapi: First pass at using modern C++.

src/cubeb_array_queue.h, src/cubeb_opensl.c, test/test_sanity.cpp
Full duplex functionality for OpenSL ES. The patch in the bottom is the same patch which backout in 99d6ae1 rebased to current version. The rest of the patches are all problems found during build, manual testing and try run. Latest try:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=cab4bbde79b65b872f0181b2076d49b3b8df231d
Latest autophone try:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=ae10057481627d78a7b47483adfc27768c985d79
Review @kinetiknz and/or @padenot ?
=> OpenSL ES full duplex restored

src/cubeb-sles.h
Missing file required to build stand alone OpenSL ES backend.
=> Add missing cubeb-sles.h file

src/cubeb_pulse.c, test/test_audio.cpp
The existing implementation called pa_cvolume_set_balance on an
uninitialized pa_cvolume (which triggered a Valgrind warning) and then
forgot to apply the result to the sink input.
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1319623
r? @achronop
=> pulse: Complete pulse_stream_set_panning implementation.

CMakeLists.txt, include/cubeb/cubeb.h, src/cubeb-internal.h, src/cubeb.c, src/cubeb_alsa.c, src/cubeb_audiotrack.c, src/cubeb_audiounit.cpp, src/cubeb_jack.cpp, src/cubeb_kai.c, src/cubeb_mixer.cpp, src/cubeb_mixer.h, src/cubeb_opensl.c, src/cubeb_pulse.c, src/cubeb_sndio.c, src/cubeb_wasapi.cpp, src/cubeb_winmm.c, test/common.h, test/test_audio.cpp, test/test_duplex.cpp, test/test_latency.cpp, test/test_mixer.cpp, test/test_record.cpp, test/test_sanity.cpp, test/test_tone.cpp
changes:
- Add a `enum` for channel layout
- Add a property in `cubeb_stream_params` to specify the channel layout
- Set `dwChannelMask` by the given channel layout in cubeb_wasapi
- Test channel layout in test_audio
=> Support multiple channels on Windows

src/cubeb_mixer.cpp, src/cubeb_mixer.h, test/test_latency.cpp, test/test_mixer.cpp
- Allow ```cubeb_get_preferred_channel_layout``` returning CUBEB_LAYOUT_UNDEFINED
- Fix typo
=> Allow preferred layout returning undefined

src/cubeb_wasapi.cpp
This caused gecko bug 1326176.
This was caused by the fact that we would null out `stm->thread` when in
fact it was still running, so we would delete `stm->emergency_bailout`
twice, because we would return true from `stop_and_join_thread`.
=> Prevent double-free when doing an emergency bailout from the rendering thread

src/cubeb_sndio.c
(see: http://stackoverflow.com/questions/17864095/c-pthread-mutex-expected-expression-before)
I got the following error on my Debian testing box:
In file included from /home/ace/projects/cubeb/src/cubeb_sndio.c:9:0:
/home/ace/projects/cubeb/src/cubeb_sndio.c: In function ‘sndio_stream_init’:
/home/ace/projects/cubeb/src/cubeb_sndio.c:248:12: error: expected expression before ‘{’ token
s->mtx = PTHREAD_MUTEX_INITIALIZER;
^
CMakeFiles/cubeb.dir/build.make:230: recipe for target 'CMakeFiles/cubeb.dir/src/cubeb_sndio.c.o' failed
=> Fix erroneous usage of PTHREAD_MUTEX_INITIALIZER

src/cubeb.c
Gecko only officially supports the PulseAudio backend, so it makes sense to
prefer that over JACK and ALSA, which are supported by contributors.
This is a partial fix for issues like [BMO #1331526](https://bugzilla.mozilla.org/show_bug.cgi?id=1331526).  A better long term fix
would allow overriding the backend selection with requests for a specific
backend.
=> Move jack_init below pulse_init in cubeb.c.

src/cubeb-internal.h, src/cubeb.c, src/cubeb_assert.h
See [bug 1332937](https://bugzilla.mozilla.org/show_bug.cgi?id=1332937), where the crash reporter is not called.
This allow using `MOZILLA_RELEASE_ASSERT` or something like that, and integrate with the crash reporter.
@kinetiknz, do you remember why we have both a null-dereference AND a call to `abort` in `cubeb_crash` ?
=> Allow using a different release assert function in cubeb.

src/cubeb_pulse.c, test/common.h, test/test_duplex.cpp, test/test_record.cpp
It solves #149. The device state is set as enabled when port is null. Tested by a contributor and works fine (Bug 1332887).
=> pulse: return state enabled when port is NULL. (Bug 1332887)

src/cubeb_resampler.cpp, src/cubeb_resampler_internal.h, test/test_resampler.cpp
@achronop and I have witnessed a number of scenarios where sometimes, instead of getting an input callback before the output callback, we have no input data when we want to render, and then right after, we get an input callback with double the amount of frames. This happens on OSX and Windows. 
Because we delay the input side by a few buffers, this works fine when resampling happens. When using a no-op resampler, because we simply forward the call to the user callback, data getting lost.
This adds a buffer in the no-op path (renamed for the occasion), and handles this case, adjusting the assert. Also, a number of tests that would have caught this are added, and another test case that simulates the scenario described above has been added.
=> Allow buffering some input when using a noop resampler, and rename it because it's not strictly no-op anymore

src/cubeb_audiounit.cpp, src/cubeb_mixer.cpp, src/cubeb_mixer.h, src/cubeb_pulse.c, test/test_latency.cpp
This is the implementation for audio 5.1 support on OS X. It only support the output side. If we also need to implement the input side, I'll add later.
=> Multiple channel support on OS X

src/cubeb_alsa.c
I'm a bit concerned about the substractions that are not checked for underflow, but this fixes the warnings.
=> Fix warnings in cubeb_alsa.c

CMakeLists.txt, src/cubeb_wasapi.cpp
Now that https://bugzilla.mozilla.org/show_bug.cgi?id=1130266 is in effect, we no longer need to support XP SP2 and Vista.
=> Drop support for Windows versions lower than 7 (XP SP2 and Vista)

src/cubeb_audiounit.cpp, src/cubeb_resampler.cpp, src/cubeb_resampler_internal.h
This patch is solving a build up latency when c920 webcam is used as external audio input. The problem occurs after some time (~10 mins) by getting extra output callbacks, consequently, extra silence in pushed in the input that creates the delay. In order to solve that I did the followings:
- Change the resampler not to store any remaining input frame, instead, return the number of the used frames. 
- Change audiounit backend to save the remaining input and use them in the following cycles. Moreover extra silence is pushed, if only the input is not enough and not when there are more output callbacks than expected. This does not allow the latency to grow.
Finally, in order to study the case I created and used 2 convenient log macros for normal and verbose async logging. This can be done …
=> Audiounit drift with c920 webcam (Bug 1329190)

src/cubeb_wasapi.cpp
This tripped up an assert in debug mode only on treeherder: https://treeherder.mozilla.org/#/jobs?repo=try&revision=9be5ea7ead43169edbbee81448e2e896d5ca1e19
Note that this try job has [a patch](https://hg.mozilla.org/try/rev/9be5ea7ead43169edbbee81448e2e896d5ca1e19) on top, that makes the assert a release assert as well as increasing the buffering.
=> Allow to prebuffer more data when in debug.

src/cubeb_wasapi.cpp
1. Don't try to re-do an emergency bailout after having done one: we don't know whether the bool has been freed or not. This has been found in the field, https://bugzilla.mozilla.org/show_bug.cgi?id=1340291. This is rather rare. One day we'll have proper atomic refptr of atomic memory maybe... 
2. `stm->output_client` and `stm->input_client` should be accessed only when the lock has been taken. During a reconfigure, we null them out ([here](https://github.com/kinetiknz/cubeb/blob/master/src/cubeb_wasapi.cpp#L1797)). Simply taking the lock before doing the assert should be enough. This is very rare, captured in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1340278
=> Fixes for two crashes

src/cubeb_audiounit.cpp
Per [discussion in pull 234](https://github.com/kinetiknz/cubeb/pull/234#discussion_r101745194), we should avoid to create another AU when we already have one in cubeb_stream, or it might cause a deadlock.
=> Prevent deadlock by avoiding creating AU when getting channel layout

src/cubeb_audiounit.cpp
This PR implements the aggregate device enhancement for full duplex operation. Aggregate device is a virtual device created from the given input and output devices and has the benefit of clock drift compensation etc. This new device is used to configure the existing AudioUnit(s).
One thing to note is that stream_init (duplex) will fail when the create of aggregate device fails. I could avoid that and fallback to the old code flow however I want to use it (probably setup telemetry in firefox) in order to figure out if (and how often) the create can fail. It never fails in my machine. I plan to remove it after a couple of weeks and allow the fallback mechanism for the Released versions.
The on going try: https://treeherder.mozilla.org/#/jobs?repo=try&revision=623acf4fb244a2b51d2e9f1572b3423a …
=> audiounit: Implement aggregate devices for duplex (Bug 1325577)

src/cubeb_wasapi.cpp
The follow up fix for Bug 1337641
=> wasapi: use DEBUG macro instead NDEBUG (Bug 1337641)

src/cubeb_audiounit.cpp
Get the volume level at the begin of reinit and set it to the newly created stream after setup.
=> audiounit: preserve volume after stream restart (Bug 1343920)

src/cubeb_wasapi.cpp
In certain windows configuration, waiting on an invalid handle crashes the caller.
This fixes gecko bug #1342389.
=> Check the emergency bailout boolean before and after the WaitForMultipleObject

src/cubeb_wasapi.cpp
=> In cubeb_wasapi.cpp, when a device has been invalidated, clear out the device pointer before trying again with the next device.

src/cubeb_audiounit.cpp
I am not able to repro the crash but I believe this patch will solve it. The truth is that we do not solve the root cause that would be not to call cubeb_destroy before every stream is stopped and destroyed (bug 1083664). In any case this patch fixes other cases like to destroy during device switch. 
Try link:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=1f819e60bed151b4ed84536aefc1c8c076b21cab
=> audiounit: add synchronization in cubeb destroy (Bug 1344580)

src/cubeb_audiounit.cpp
Lock cubeb mutex during reinit stream. This add synchronization between the reinit and the stream_start/stop/init/destroy. I believe that causes the crash in Bug 1343930 but I did not manage to repro in order to verify.
=> audiounit: context synchronization in reinit stream

src/cubeb_audiounit.cpp
In audio callback, when returned frames are less that the expected we go to Drain. However if return frames are less than zero or more than expected we should go to error.
=> audiounit: On unexpected number of returned frames go to error

CMakeLists.txt, src/cubeb_wasapi.cpp, test/test_overload_callback.cpp
This fixes Gecko bug #1345147.
=> Make `stop_and_join_render_thread` more idempotent, and add a test.

include/cubeb/cubeb.h, src/cubeb.c, test/test_audio.cpp, test/test_devices.cpp, test/test_duplex.cpp, test/test_latency.cpp, test/test_overload_callback.cpp, test/test_record.cpp, test/test_sanity.cpp, test/test_tone.cpp
This allows forcing of a particular backend by name,
*if* it was compiled in, otherwise default list is tried
in default order as before.
Tests updated to reflect new api.  (Gecko change required)
100% tests passed (using JACK backend)
Signed-off-by: Damien Zammit <damien@zamaudio.com>
=> api: Give cubeb_init a third param, backend name (Bug 1341238)

src/cubeb_ringbuffer.h, test/test_ring_buffer.cpp
This annotates ring_buffer_base's various loads and stores from the read and write indices with the narrowest memory ordering that particular load or store requires, rather than accepting the default  memory_order_seq_cst everywhere.  This avoids generating numerous unnecessary memory barriers (the x86 impl is now barrier free, and the ARMv7 impl has half as many barriers), which has a positive effect on performance.
Tested on RPi3 and i7-3720QM.
Note that I took the lazy path of removing the non-lock-free variants of ring_buffer_base since we don't use it (except in the test) and I don't know if there are specific plans to use it.  It's probably possible to keep it with more template magic to let us use the methods on std::atomic<T>, but the code is simpler with that aspect of genericity …
=> Avoid generating unnecessary memory barriers in ring_buffer_base

src/cubeb_audiounit.cpp
AudioUnit is not initialized in audiounit_get_preferred_channel_layout since it's not assigned to nullptr before passing it to audiounit_create_unit.
=> Assigning AudioUnit to nullptr before passing it to audiounit_create_unit

test/test_overload_callback.cpp
It's better to use
- gtest's assertion than c style assert in gtest
- ```fprintf(stderr, ...)``` than ```printf(...)```
=> Replace assert by gtest's assertion

src/cubeb.c
Used to select the rust version of pulse audio backend.
Enabled by defining USE_PULSE_RUST.
=> Add extern pulse_rust_init.

src/cubeb_log.cpp
Fix an out-of-bounds write by removing and extra +1 which was causing a \0
to be written out of |storage| in edge cases.
Patch by @BurningMind.
=> Bug 1349527 - Remove an extra +1 in cubeb_log_message::cubeb_log_message()

CMakeLists.txt
This was really written with WASAPI in mind, to test the emergency boolean. That said, we'd better implement overflow and underflow detection at some point, for all backends.
This fixes #264.
=> Only compile and run 'test_overload_callback' when compiling in WASAPI

src/cubeb_audiounit.cpp
Layout is set in the output parameter and return CUBEB_OK. Accidentally we returned the layout itself.
=> audiounit: Set layout in output argument.

src/cubeb_audiounit.cpp
This addresses [BMO bug #1339537](https://bugzilla.mozilla.org/show_bug.cgi?id=1339537#c16), which aims to ban passing structs containing
alignas members by value.  The analysis for this is tripped up by libc++'s
implementation of std::function.
Since we're the only place in Gecko hitting this, and have no real need for
std::function here, the simplest solution is to switch to a bare function
pointer.
=> audiounit: Prefer a bare function pointer over std::function.

src/cubeb_wasapi.cpp
Fixes #262: Capture stream freezes on WASAPI when resampling.
The previous behavior would return false (and thus stop all future
callbacks) if the user didn't process all frames in linear_input_buffer.
This could erroneously happen when the resampler held back frames for
the next batch (e.g. 448 input frames at 44.1 KHz upsampled to 48 KHz,
which doesn't have a perfect integer scale), so the user callback didn't
have access to all of the current linear input frames.
The refill() function already handles the case where the user callback
returns less than the number of frames passed in (by settings
stm->draining), so this commit changes the callback_input() return value
to defer to that.
=> WASAPI: make callback_input return !stm->draining

test/common.h, test/test_audio.cpp, test/test_devices.cpp, test/test_duplex.cpp, test/test_latency.cpp, test/test_overload_callback.cpp, test/test_record.cpp, test/test_tone.cpp
Apply RAII helpers for cubeb context and stream in most test cases but leaving test_sanity for explicit flow control.
=> Using RAII helpers for cubeb context and stream in the test

test/test_duplex.cpp, test/test_mixer.cpp, test/test_record.cpp, test/test_resampler.cpp, test/test_sanity.cpp, test/test_tone.cpp
- Perfer ```fprintf(stderr, ...)``` instead of ```printf(...)```
- Turn the error message into gtest's style
We have many patterns like the following:
```
if (r != CUBEB_OK) {
fprintf(stderr, "Error initializing cubeb stream\n");
ASSERT_EQ(r, CUBEB_OK);
}
```
We should replace them by:
```
ASSERT_EQ(r, CUBEB_OK) << "Error initializing cubeb stream";
```
=> Using gtest style's error message in cubeb

src/cubeb_audiounit.cpp
Same thing as #262/#263, but for the CoreAudio backend.
Might be a useful to change the definition of `cubeb_resampler_fill` at some point to make clear what the number of frames handled should be compared against.
=> audiounit: make input_callback read correct number of frames handled

src/cubeb_opensl.c
This might address issue #278.
=> opensl: Rename __system_property_get wrapper to avoid build issues.

src/cubeb.c, src/cubeb_audiounit.cpp, src/cubeb_mixer.cpp, src/cubeb_mixer.h, src/cubeb_utils.h, src/cubeb_wasapi.cpp, test/test_audio.cpp, test/test_overload_callback.cpp, test/test_sanity.cpp, test/test_tone.cpp
Brings the WASAPI backend up to parity with the other backends, making it easier to write cross-platform code for S16 audio. I tried to base my approach off of the AudioUnit backend (in fact, `auto_array_wrapper` is now in cubeb_utils and used by both) and a little bit from the Jack backend (the `bytes_per_sample` member).
The official documentation is (purposefully?) obtuse as to when S16 is a supported format, but it seems to hint that it's always available in non-exclusive  mode, and the rest of the internet seems to believe that that's true.
=> wasapi: Implement S16NE-format streams

src/cubeb_sndio.c
Fairly unlikely to happen, but may as well cover all bases anyways.
=> cubeb_sndio: Fix leak in sndio_stream_init() failure case

src/cubeb_wasapi.cpp
Corrects an accidental duplicate, which would prevent enumerating both rendering and capturing endpoints.
=> cubeb_wasapi: Correct duplicate bitwise OR entry in wasapi_enumerate_devices()

src/cubeb_audiounit.cpp, test/test_deadlock.cpp
- Replace RAII with unique_ptr in ```test_deadlock.cpp```
- Remove .get() for unique_ptr in ```cubeb_audiounit.cpp```
=> some cleanup

src/cubeb_audiounit.cpp
Add a unique id for the device name and UID of the newly created aggregate device. This is necessary when more than one aggregate device functioning in the same time. If the name and UID are the same the second aggregate device fails to be configured. For unique id used the pointer address of the plug in id. BMO #1355306.
=> audiounit: Add unique id in aggregate device name and UID.

src/cubeb_wasapi.cpp
The ```mix_format``` returned from ```IAudioClient::GetMixFormat``` is the hardware-supported format for the stream, so we should not crash the stream on purpose if the user's audio sound card supports N-channel recording, where N > 2.
If we intend to crash a N-channel recording stream, we should check ```stream_params->channels``` instead of ```mix_format->nChannels```.
=> Enable multichannel recording if it's hardware-supported

src/cubeb_audiounit.cpp, src/cubeb_mixer.cpp, src/cubeb_mixer.h
Without this, trying to play audio on a device that has more than 8 output channels trashes some memory and crashes.
With this patch we can use [SoundFlower](https://github.com/mattingalls/Soundflower/releases) to test multi-channel support, and to do nice things like, generating audio in a fake input device, recording the output device using another program test, etc. 
@ChunMinChang, want to have a look ? I plan to do the same for Windows after this, reading the code, it must have the same issue. I will have my windows machine next week, though.
=> Make cubeb work with high channel count devices

src/cubeb_wasapi.cpp
The ```close_wasapi_stream``` and ```setup_wasapi_stream``` will be fired on a device change. Originally, we initialized ```stm->mixing``` in ```wasapi_stream_init``` and destroy them in ```close_wasapi_stream```. Thus, the ```stm->mixing``` will be **nulled** upon device is changed, while the stream is still playing, and the crash happens when we use a nulled ```stm->mixing``` to up/downmix audio.
=> Fix crash while switching device

src/cubeb_audiounit.cpp, src/cubeb_mixer.cpp, src/cubeb_mixer.h, src/cubeb_wasapi.cpp, test/test_mixer.cpp
Since we have similar patterns to call up/downmixing in ```cubeb_wasapi.cpp``` and ```cubeb_audiounit.cpp```, it will be easier to maintain the code if we have an identical interface and use it in both backends.
=> Use same mixer interface for wasapi and audiounit

src/cubeb_wasapi.cpp
See https://bugzilla.mozilla.org/show_bug.cgi?id=1358868#c4 for the rational behind this.
=> Return an error if stopping a WASAPI stream fails.

src/cubeb_mixer.cpp
When I test the latest cubeb with Firefox, I see an assertion failed:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=48fcebbf30da5c3dcae0691856cbb1ac7ca467f5&selectedJob=96806605
It indicates the ```inframes``` for ```cubeb_upmix``` may be ```0```.
I think we should early return in this case.
https://treeherder.mozilla.org/#/jobs?repo=try&revision=2b2f3ac90243bdfa3ce9ac2e00d09e4807942ab5&selectedJob=96819342
To help debugging, some assertions should be breakdown
=> Do not mix audio when no frames come

src/cubeb_audiounit.cpp
1. Make sure there is an ouput unit when request volume on reinit. This prevent an assert on input only methods.
2. Don't reinit on datasource event. By testing I realized that the platform is able to handle the case more efficient than the manual reinit. The device ids of input and/or output remain the same.
=> audiounit: volume and datasource fixes on reinit

src/cubeb_audiounit.cpp
There are many crash reports about UAF in reinit. In addition bug 1361657 provide ASAN logs of the error which is pretty explanatory.
In this patch I changed stream destroy to close the stream in the same serial queue that reinit takes place. I removed also the unregister of stream listener before that and outside the effect of any mutex.
=> audiounit: synchronize destroy stream and reinit (Bug 1361657)

src/cubeb_wasapi.cpp
- The ```IAudioClient``` used in ```handle_channel_layout``` should be adjusted depending on the stream is input or output.
- It's allowed to use undefined layout for input stream, so ```XASSERT(stm->input_stream_params.channels == CUBEB_CHANNEL_LAYOUT_MAPS[stm->input_stream_params.layout].channels);``` should be removed.
=> Fix handle_channel_layout for input stream

CMakeLists.txt, include/cubeb/cubeb.h, src/cubeb-internal.h, src/cubeb.c, src/cubeb_alsa.c, src/cubeb_audiotrack.c, src/cubeb_audiounit.cpp, src/cubeb_jack.cpp, src/cubeb_kai.c, src/cubeb_opensl.c, src/cubeb_pulse.c, src/cubeb_sndio.c, src/cubeb_utils.c, src/cubeb_utils.h, src/cubeb_wasapi.cpp, src/cubeb_winmm.c, test/common.h, test/test_devices.cpp
In preparation for string interning of device id for selected backends, move the common cubeb_device_collection_destroy logic to backends. This allows for allocation other than malloc/free and having strings that statically allocated in cubeb_device_info.
To being with all backends use the same, default cleanup code from cubeb_utils.
=> Push destroy fns to backend

test/common.h, test/test_audio.cpp, test/test_deadlock.cpp, test/test_devices.cpp, test/test_duplex.cpp, test/test_latency.cpp, test/test_overload_callback.cpp, test/test_record.cpp, test/test_sanity.cpp, test/test_tone.cpp
Set CUBEB_BACKEND env var to the name of valid backend supported by
the current platform to prefer that backend over the default choice.
If CUBEB_BACKEND is not valid, backend selection falls back to the
standard behaviour.
A warning is printed to stderr if the chosen backend id doesn't match
the requested one.
(Issue #306)
=> Add backend specification support to common.h

src/cubeb_audiounit.cpp, src/cubeb_mixer.cpp, src/cubeb_mixer.h, src/cubeb_wasapi.cpp, test/test_mixer.cpp
The ```AudioUnit``` allows us to set the layout containing other channels that the output device can **not** provide. For example, setting *3F2-LFE* layout to a stereo device is fine. When the audio is played, those channels beyond stereo(*Center*, *LFE*, *Left Surround*, *Right Surround*) will be dropped. 
To keep all the information, we need to mix those audio data before it's dropped. That's what we do in #234. We mix the audio before it's played and dropped. In above case, we mixed the audio in *Center*, *LFE*, *Left Surround*, *Right Surround* into *Left* and *Right* channels before playing, while other channels are not be changed. That is,
```
+----+----+----+------+-----+-----+----+----+----+------+-----+-----+
| L0 | R0 | C0 | LFE0 | LS0 | RS0 | L1 | R1 | C1 | LFE1 | LS1 | RS1 | …
```
=> Add osx-specific setting for downmixing test

test/test_latency.cpp, test/test_sanity.cpp
We used to test ```cubeb_get_preferred_channel_layout``` in ```test_latency.cpp```, however, the latency doesn't be affected by the layout. It's more reasonable to test it in ```test_sanity.cpp```
=> Test cubeb_get_preferred_channel_layout in test_sanity instead of test_latency

src/cubeb_wasapi.cpp
In duplex callback we used to pass through the number of samples instead of frames. This is ok on MONO but it does not work on STEREO capture.
P.S. I need this fix for the stereo gum bug. It will be great to get a quick review. I plan to import it to gecko as soon as possible.
=> wasapi: use number of frames instead of samples

src/cubeb_mixer.cpp, test/common.h, test/test_mixer.cpp
- Fix #314 
- Fix warnings of comparison of integers of different signs
- Add debugging messages
=> Fix test_mixer fails on local build

src/cubeb_audiounit.cpp, test/test_deadlock.cpp, test/test_duplex.cpp, test/test_record.cpp, test/test_tone.cpp
Clear TSAN warnings for audiounit backend. Full list of warnings can be found in #317.
=> audiounit: clear tsan warnings

src/cubeb_wasapi.cpp
It was converting to milliseconds, not hundred-nanoseconds.
=> wasapi: fix frames_to_hns

src/cubeb_audiounit.cpp
I investigate the following assert crashes [here](https://crash-stats.mozilla.com/signature/?version=55.0b&version=55.0b1&version=55.0a1&version=56.0a1&proto_signature=~___ZL36audiounit_property_listener_callbackjjPK26AudioObjectPropertyAddressPv_block_invoke&signature=libsystem_kernel.dylib%400x15866&date=%3E%3D2017-05-11T13%3A45%3A00.000Z&date=%3C2017-06-15T13%3A45%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_sort=-date&page=1#reports)
The assert will show if there is any chance to get stream_reinit block before the stream_close block in serial queue.
=> audiounit: assert that I/O AU is not NULL in reinit

CMakeLists.txt
This fixes an error when using the installed headers causing it to not find cube_export.h because it is actually located in `${CMAKE_INSTALL_PREFIX}/exports/cubeb_export.h` instead of `${CMAKE_INSTALL_PREFIX}/cubeb_export.h`
=> Fix exports not being in the same directory as cubeb.h

include/cubeb/cubeb.h, src/cubeb-internal.h, src/cubeb.c, src/cubeb_alsa.c, src/cubeb_audiotrack.c, src/cubeb_audiounit.cpp, src/cubeb_jack.cpp, src/cubeb_kai.c, src/cubeb_opensl.c, src/cubeb_pulse.c, src/cubeb_sndio.c, src/cubeb_wasapi.cpp, src/cubeb_winmm.c
Per discussion on [bug 1361336](https://bugzilla.mozilla.org/show_bug.cgi?id=1361336#c48), for now, we need to add a new API to reset the audio streams to the default device until the [remote work](https://bugzilla.mozilla.org/show_bug.cgi?id=1362220) is finished.
=> New API to reconfigure the audio stream to the default device

src/cubeb_audiounit.cpp
StackedKey is set to 0 in order arrange sub-devices of the AudioAggregateDevice such that the output streams are all fed the same data.
Output device is listed before input in order to make output device's stream the default.
Bug 1375729
=> audiounit: default to output stream on aggregate devices

src/cubeb_audiounit.cpp
Fix for crash in Bug 1385448. The crash blocks all webrtc calls in today's Nightly. I would appreciate a quick review.
=> audiounit: set id when it's not the default

src/cubeb_wasapi.cpp
This addressed BMO #1362764, which was detected as heap corruption resulting in crashes when releasing IAudioClient or related interfaces on shutdown.
=> wasapi: Handle GetMixFormat returning non-WAVEFORMATEXTENSIBLE pointers.

src/cubeb_pulse.c
suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
=> Fix a gcc warning with -Wparentheses

src/cubeb_log.cpp, src/cubeb_log.h, src/cubeb_ringbuffer.h, src/cubeb_wasapi.cpp, test/test_ring_buffer.cpp
This allow reseting the consumer/producer thread id in the ring buffer
class, so that we can take into account the change in thread inherent to
the audio devices changes.
This fixes #320.
=> Add a thread reset API for the ring buffer class.

src/cubeb_wasapi.cpp
Map it to KSAUDIO_SPEAKER_DIRECTOUT, which means that the speakers are
considered discrete entities and not part of a specific layout.
=> Allow passing in CUBEB_LAYOUT_UNDEFINED as layout for the output side in WASAPI

src/cubeb_audiounit.cpp
Due to Bug 1398788 full reinit is performed on DataSource event like we did in the past.
=> audiounit: reinit stream on DataSource event (Bug 1398788)

src/cubeb_audiounit.cpp
Satisfy an assert when reinit on playback scenario. In the fix we check which side is on and request restart on the corresponding devices.
=> audiounit: fix assert for reinit on playback (Bug 1400465).

src/cubeb_pulse.c
Set default_sink_name and default_source_name to a valid string
pointer or NULL after free'ing previous values.
(Requested by @achronop in comments on PR #360)
=> pulse: Cleanup potentionally dangling pointers.

src/cubeb_resampler.cpp, src/cubeb_resampler_internal.h, test/test_resampler.cpp
For now, it leaves at most 100ms in the buffer. It seem to behave well. I've used this to test:
```diff
diff --git a/test/test_duplex.cpp b/test/test_duplex.cpp
index 427b503..f17634d 100644
--- a/test/test_duplex.cpp
+++ b/test/test_duplex.cpp
@@ -17,11 +17,14 @@
#include <memory>
#include "cubeb/cubeb.h"
#include "common.h"
+#include <iostream>
#include <atomic>
#define SAMPLE_FREQUENCY 48000
#define STREAM_FORMAT CUBEB_SAMPLE_FLOAT32LE
+static std::atomic<int> rounds = 0;
+
struct user_state_duplex
{
std::atomic<int> seen_audio{ 0 };
@@ -50,7 +53,11 @@ long data_cb_duplex(cubeb_stream * stream, void * user, const void * inputbuffer
output_index += 2;
}
-  u->seen_audio |= seen_audio;
+  for (uint32_t i = 0; i < nframes * rounds; i++) {
+    if (ib[i % nframes] <= -1.0 && ib[i % …
```
=> Implement some rudimentary underrun protection for duplex streams

CMakeLists.txt, Config.cmake.in
I modified CMakeLists.txt to support generating and installing CMake config files. These config files should make using cubeb from other CMake projects much easier.
=> CMake: Generate and install CMake config files

test/test_deadlock.cpp
Mute it or become deaf on local test execution.
=> Mute test deadlock

INSTALL.md
Add mention of visual studio 2017, add instructions on how to use CMake from within VS2017. Point out gotcha of default build dirs in VS2017.
=> Elaborate the build instructions for Windows

src/cubeb_audiounit.cpp
Return CUBEB_ERROR when set device info fails on reinit. This is expected when the last media device is unplugged.
=> audiounit: reinit fail when no media devices (Bug 1409224)

src/cubeb_audiounit.cpp
On failed reinit we go to error instead of stop state. This will align the behavior with the other backends.
=> audiounit: change state to error on failed reinit.

src/cubeb_audiounit.cpp
The default sample rate given to a newly created aggregate device is the sample rate of the device listed first. If one of the devices in the group does not support that sample rate the result is distortion.
This patch query both devices for min/max/nominal sample rates and configure a compatible rate for both devices. If there is no compatible sample rate it fails nicely. 
See Bug 1411535.
=> audiounit: on aggregate device use a sample rate compatible for both devices

include/cubeb/cubeb.h
The sample code in the header looks to have a few instances where
'output_params' is used where 'input_params' looks intended. This renames
those cases.
=> Update header sample code to rename several instances of output_params -> input_params.

src/cubeb_audiounit.cpp
Oneliner, ridiculous error slipped off from previous commit. On reinit reset output device when output stream is on (not input).
=> audiounit: correct output device reset (Bug 1421206)

src/cubeb_wasapi.cpp
Band aid WASAPI channel mappings so that KSAUDIO_SPEAKER_QUAD and KSAUDIO_SPEAKER_5POINT1 are handled rather than returning undefined. Addresses https://github.com/kinetiknz/cubeb/issues/383.
=> WASAPI: handle KSAUDIO_SPEAKER_QUAD and KSAUDIO_SPEAKER_5POINT1 channel mapping

src/cubeb_wasapi.cpp
Return early from `refill_callback_duplex` when `stm->draining` is `true`
=> wasapi: return early on draining for duplex callback

src/cubeb_audiounit.cpp
Updating device nominal rate for aggregate device (AD) updates the sampling rate of the devices that AD is consisting of. If the device does not support the given rate the update fails. This patch does 2 things: (a) does not attempt to change the nominal rate of an AD if it is the same with output device rate (output is the master device so the rate will set to that anyway) (b) handle the update failure as non fatal failure.
Update of nominal sample rate for AD used in order to fix a dysfunction on Airpods device but the way that it works makes me wonder if we should ever attempt to change it. I push that fix in order to avoid some known failures and I will continue investigating a better way to approach the problem from the beginning.
cc @djg
=> audiounit: Change AD nominal rate only when is needed

src/cubeb_wasapi.cpp
The object allocated by ```new``` should be deallocated by ```delete``` instead of ```free```.
=> Replace free by delete to prevent potential memory leak 

src/cubeb_pulse.c
When `pa_context_subscribe` fails we need to unlock the main loop to avoid infinite blocking.
=> pulse: avoid deadlock when context subscribe fails

src/cubeb_mixer.cpp
In the current implementation, only stereo channel will have data. Those channels beyond stereo will be silenced. We should pass through as more data as possible.
=> Fix issue 378: Pass through as more data as possible when upmixing

src/cubeb_wasapi.cpp
Increase initial silence on debug for wasapi to avoid intermittent described by bug 1393740
=> wasapi: increase initial silence on debug

src/cubeb_winmm.c
Think we can end up with a nullptr deref at `if (output_stream_params->channels > 2) {`.
Wasn't sure if this should be an assert or an early return. Please advise if early return is preferred.
=> Add assertion to make sure output params are present for winmm_stream_init

CMakeLists.txt, include/cubeb/cubeb.h, src/cubeb_alsa.c, src/cubeb_audiounit.cpp, src/cubeb_jack.cpp, src/cubeb_kai.c, src/cubeb_opensl.c, src/cubeb_pulse.c, src/cubeb_sndio.c, src/cubeb_wasapi.cpp, src/cubeb_winmm.c, test/test_audio.cpp, test/test_deadlock.cpp, test/test_devices.cpp, test/test_duplex.cpp, test/test_latency.cpp, test/test_loopback.cpp, test/test_mixer.cpp, test/test_overload_callback.cpp, test/test_record.cpp, test/test_resampler.cpp, test/test_sanity.cpp, test/test_tone.cpp
Expose a new preference member on `cubeb_stream_params`. Allow callers to specify preference for a loopback device for a (input) stream. Implement loopback devices for the WASAPI backend. Add a number of tests.
Note: Locally, I had some issues with channel layout that I remedied via: https://github.com/kinetiknz/cubeb/pull/384. This PR does not require these changes, but if you encounter problems it may be worth checking if they're related.
The following are outstanding questions that should be discussed (and the PR updated):
Please let me know if you have any queries or feedback.
=> Add loopback pref and an impl for the WASAPI backend

src/cubeb_audiounit.cpp, test/test_duplex.cpp
- Fix deadlock when creating a duplex stream when a device collection change callback was installed
- Stop calling this callback when creating a duplex stream (the fact that we create a device internally should not be exposed), and add a test for it.
- sed 's/std:://' since I added `using namespace std;`.
=> Fix deadlock and device collection changed callback issue on OSX 

src/cubeb_wasapi.cpp
Device invalidated error can occurs in many case and the documentation suggests to reset the stream. More info in Bug 1426333. This is implemented on commit 1fb675.
The other two commits are complementary patches that add an error check and 2 log lines.
=> Wasapi reset stream on invalidated device error

include/cubeb/cubeb.h, src/cubeb.c, src/cubeb_alsa.c, src/cubeb_audiotrack.c, src/cubeb_audiounit.cpp, src/cubeb_jack.cpp, src/cubeb_kai.c, src/cubeb_opensl.c, src/cubeb_pulse.c, src/cubeb_sndio.c, src/cubeb_wasapi.cpp, src/cubeb_winmm.c
cubeb_stream in every backend has a copy of the user data ptr passed
in during `stream_init` but there is no way to access the
value. (Besides from `data_callback`/`state_callback`).
Add `cubeb_stream_user_ptr()` to retrieve the stored value.
=> Provide access to cubeb_stream's user ptr.

CMakeLists.txt, src/cubeb-jni-instances.h, src/cubeb-jni.cpp, src/cubeb-jni.h, src/cubeb_opensl.c
Bug 1410456: OpenSL ES backend must not access the system library libmedia.so. The following method implementations have to be removed:
get_preferred_sample_rate()
get_min_latency()
stream_get_latency()
User of the libabry must get this information from jni.
=> OpenSL ES remove lib access

src/android/cubeb-output-latency.h, src/android/cubeb_media_library.h, src/cubeb_opensl.c
Keep the old mechanism for version 4.2 and lower. The getOutputLatency method of AudioManager is not available there. This fixes the backout of Bug 1410456.
=> opensl: keep media lib access for older versions

src/cubeb-jni-instances.h, src/cubeb-jni.cpp
JNIEnv struct is per thread and we need to detach any thread previously attached. Since cubeb is a library we have no control on the thread that initialized cubeb itself. Detaching a working thread is a crash or leaving an attached thread un-detached is also a crash. So we leave to the user the implementation of providing the right JNIEnv pointer for each thread and perform the attach and detach correctly. There is a standard way to implement that using pthread functionality. In Firefox this is implemented in method `mozilla::jni::GetEnvForThread()`.
=> opensl: Pass in JNIEnv instead of JavaVM

CMakeLists.txt, include/cubeb/cubeb.h, src/cubeb_audiounit.cpp, src/cubeb_wasapi.cpp, test/test_callback_ret.cpp
The description of the ret value of cubeb_data_callback specifies that it is the number of frames written to the output buffer. However, in the input only stream case no data should be written to the output buffer and the output buffer arg will be NULL.
This leaves it unclear as to the value that should be returned in the input only case. ~To prevent a drain nframes should be returned~ (this appears to not be the case for input only, please see discussion below), however, reading the documentation left me unsure as to if I should return 0 or nframes.
This commit attempts to clarify the doc comment for input only streams.
=> Clarify cubeb_data_callback ret value for input only streams.

src/cubeb_audiounit.cpp
Some devices (namely, Bose QC35, mark 1 and 2), expose a single channel mapped
to the right for some reason, and this confuses our channel mapping code.
This fixes bugzilla bug [#1429725](https://bugzilla.mozilla.org/show_bug.cgi?id=1437366#c9).
=> When having on or two channel, force mono or stereo.

test/test_loopback.cpp
- For the silent loopback test we check that we don't get any sound above an
epsilon. The value of this epsilon has been increased to accommodate a wider
range of systems.
- The delay on all tests has been increased to allow for more time to capture
looped samples. The original 150ms delay was sufficient on the machine I tested
with, however, I've seen the tests fail due to not having enough looped input.
=> Relax some of the checks in the loopback test to avoid false positives.

include/cubeb/cubeb.h, src/cubeb_wasapi.cpp, test/common.h
This addresses the thread local COM initialization lifetime problem discussed in issue #416 by moving the responsibility for COM initialization from within cubeb to the caller.
This needs minor changes on the Gecko side to ensure COM is initialized from all calling threads.  That's tracked in [BMO 1445546](https://bugzilla.mozilla.org/show_bug.cgi?id=1445546).
=> wasapi: Remove COM initialization and require caller to complete.

src/cubeb_mixer.cpp, src/cubeb_mixer.h
These specifiers were dropped in the @jyavenard patch shuffle from gecko.
=> Change cubeb_mixer_mix input to be const void *

src/cubeb_pulse.c
In `src/cubeb_pulse.c` many calls to PA API never check return codes. I discovered this while I was debugging why Firefox crashes with my "superior reimplementation" of libpulse API (https://github.com/oxij/libcardiacarrest). This is the I needed for my use case. However, if you look at PA API documentation, you'll notice that not only cubeb_pulse.c ignores some PA errors, it is not entirely clear whenever all of the uses of PA API in cubeb_pulse.c are even correct. For instance, is it ok to `drain` the `pa_context` before it successfully connected to the PA daemon? I'm not sure. cubeb_pulse.c `drain`s it anyway.
(Adapted from https://bugzilla.mozilla.org/show_bug.cgi?id=1444519.)
=> pulse: check pa_context_connect return value

src/cubeb_audiounit.cpp
It turns out that there are subtleties to iterating the channel bitset that I messed up in a previous commit.
The use of while was trying to be *too* clever and `i` was being used in two places with different intent, so split `i` into `i: the current bit position` and `channels: the current channel index in mChannelDescriptions`.
`channels` is @jyavenard naming that I changed, so switching back to it.
=> audiounit: Fix up channel layout iteration logic.

src/cubeb_wasapi.cpp
Cubeb instance will fail to initialize when all playback devices are disabled even if there are capture devices available. This is because wasapi_init() method checks for default playback as an indirect way to verify that wasapi is enabled in the platform. In this patch if get default playback fail we check again for the default capture device.
=> wasapi: check for default playback or capture device on init

src/cubeb_audiounit.cpp
`active_streams` counter is an atomic but it is required to change under the stream lock in order to be synchronized with the other set of actions that are taking place during stream initialization. This is found in [Bug1462210](https://bugzilla.mozilla.org/show_bug.cgi?id=1462210).
=> osx: increase active streams counter under stream lock, BMO 1462210.

src/cubeb_sndio.c
Apply volume in software as do other backends. This is necessary
because sndio volume may be controlled externally and there's no
volume getter in libcubeb to notify the caller about volume
changes.
Cf https://bugzilla.mozilla.org/show_bug.cgi?id=1467882
=> Fix volume handling in sndio backend

src/cubeb_winmm.c
This define was added as part of commit d2c45250 and is mingw-specific (only mingw uses __MSVCRT_VERSION__). I don't know why it was added, it shouldn't be needed.
Recently mingw-w64 added support for UCRT-based toolchains. In this case __MSVCRT_VERSION__ is set to 0x1400 and should not really be changed. UCRT-based builds support a lot of stdio.h function by inline wrappers. Those can't be disabled just for one file as they are not exported by ucrtbase.dll.
I found the problem while working on porting Firefox to clang+mingw-w64 toolchain that uses UCRT by default.
=> cubeb_winmm.c: Don't define __MSVCRT_VERSION__.

src/cubeb_audiounit.cpp
Add a new method to clean up when the stream init is failing. This method differs from stream destroy method, which used to do the clean up, in the fact that it expects that context's mutex is being locked and does not attempt to stop the stream.
=> audiounit: new method on failed stream init to avoid deadlock (BMO 1470113).

src/cubeb_wasapi.cpp
See [bug 1465617 comment 20](https://bugzilla.mozilla.org/show_bug.cgi?id=1465617#c20) for the background for this change.
In short the Firefox shutdown hang monitor also times out after 5 seconds by default, so cubeb has to timeout faster or confusing almost-coherent stacks show up in crash-stats.
=> wasapi: Reduce timeout threshold

src/cubeb_audiounit.cpp, src/cubeb_mixer.cpp
The method kAudioUnitProperty_AudioChannelLayout used to retrieve the channel layout wasn't introduced until 10.12. So we use kAudioDevicePropertyPreferredChannelLayout instead should it fails.
Fixes #448
=> Fix for #448

src/cubeb_audiounit.cpp, test/test_devices.cpp
1. Add a simple test for ```cubeb_stream_get_current_device(...)```
2. Reduce duplicate code for input and output in ```audiounit_stream_get_current_device(...)```
=> Reduce duplicate code in audiounit_stream_get_current_device

src/cubeb_audiounit.cpp
```audiounit_add_listener(...)``` and ```audiounit_remove_listener(...)``` should use exactly same variable to register and unregister event listener. Originally, these two functions are set by different local variables with same values: ```audiounit_add_listener(X, Y, Z, ...)``` and ```audiounit_remove_listener(X', Y', Z', ...)```, where X = X', Y = Y',...etc. There are too many function parameters so it's not easy to check if we have same parameters for ```audiounit_add_listener(...)``` and ```audiounit_remove_listener(...)```.
```property_listener``` is introduced to simplify the parameter issues by using ```audiounit_add/remove_listener(property_listener L)```. A property_listener object L is created to register a event listener, and then be used to unregister the listener later. …
=> Simplify audiounit_add/remove_listener() by introducing property_listener

.gitignore, src/cubeb_audiounit.cpp
Lots of issues discovered during the course of this.
I hope I've resolved them all.
Removing microphone/replugging used to give me a 1 in 5 crash.
Sometimes gecko's AudioCallBackDriver would reset cubeb in a loop due to a race due to how errors were propagated and reinit task pending.
Can connect on the fly BT headset and disconnect (it then defaults to the default system input)
=> More fixes for bug 1489052

src/cubeb_audiounit.cpp
In a verbose log line inside output callback we were touching input buffer which were causing a crash on playback case where input buffer is NULL.
=> audiounit: avoid access to input buffer on playback case (BMO 1496282)

src/cubeb_audiounit.cpp
Collection changed callback did not handle correctly removed devices. This is because we verify that callback has not been triggered due to adding/removing of the Aggregate Device before reporting a device changed callback .
In this fix I have removed the enumeration of the AD completely so devices comparing includes "actual" devices. Any difference on the actual device will trigger a callback.
=> audiounit: report removed devices correctly (BMO 1491152)

CMakeLists.txt, src/cubeb.c
If the `cubeb-pulse-rs` repo is available in `cubeb/src` build the project with `USE_PULSE_RUST` and link `libcubeb_pulse` to `libcubeb`.
The author of the patch is @djg , I am only pushing it.
=> Build and link pulse rust backend if available.

src/cubeb_audiounit.cpp
Use separate callback for input and output devices. This will allow to register a context with different notification callbacks for different type of devices.
See also: #464
=> audiounit: separate input output callbacks for collection changes (BMO 1498242)

include/cubeb/cubeb.h
Missing update in docs to reflect the changes in `cubeb_register_device_collection_changed`.
=> doc: update docs for register collection changed callback. Fixes 42

src/cubeb_audiounit.cpp
Fix the crash describing by the following crash-stat:
https://crash-stats.mozilla.com/report/index/264771fe-ade3-41f6-baf8-92fff0181005
=> osx: close the stream before calling setup (BMO 1500109)

src/cubeb_audiounit.cpp
Check for null reference. Fixing crash:
https://crash-stats.mozilla.com/report/index/d4e665aa-1cd7-4547-95b6-877670181023
=> osx: check null reference before using the string (BMO 1502165).

src/cubeb_mixer.cpp
PLII mix the opposed channel with the reversed phase. It doesn't sound good when used with a common stereo headset; like the left rear channel sounds too much like it's also coming from the right. Additionally, it clips significantly causing unwanted distortion. So we default to a simpler conversion instead: left goes to left only, same for the right channel.
(Part of the fix for BMO 1509875)
Fixes #476
=> Don't use PLII matrices when downmixing.

CMakeLists.txt, src/cubeb_audiounit.cpp, test/test_device_changed_callback.cpp
Creating a test to make sure `device_changed_callback` works as what we expected and it can also be used to check Rust's `device_changed_callback` implementation.
=> Test stream register device changed callback

src/cubeb_audiounit.cpp
When `audiounit_create_device_from_hw_dev` is called in an internal method we need to manually delete the allocated memory. When the same method is called from the external API method `audiounit_enumerate_devices` we don't need that because delete will happen on `audiounit_collection_destroy`.
=> audiounit: stop leaking after calling audiounit_create_device_from_hw_dev. Fixes #482

src/cubeb_pulse.c
In PulseAudio when channel layout is not specified a default is being used. If default layout is not set `stream_init` will fail. On PA channel I was recommended to use a channel layout instead of relying on default because it is not guaranteed to be set. This patch will check if a default layout exists, if not a layout is set. The default layouts have been taken from Gecko's default layout in playback (link bellow):
https://searchfox.org/mozilla-central/rev/6e0e603f4852b8e571e5b8ae133e772b18b6016e/dom/media/AudioConfig.cpp#75
=> pulse: guess default layout when it is not configured (BMO 1518106).

src/cubeb_wasapi.cpp
Per cubeb.h#L414, COM must be initialized by the caller before calling
cubeb_init.
This assert is intended to avoid unintentional fallback to the winmm backend
when the caller forgot to initialize COM before calling cubeb_init.
Inspired by issue #492.
=> wasapi: Assert COM is initialized in wasapi_init.

src/cubeb_audiounit.cpp
I found some memory leaks by running the *Instruments* on OSX.
- The `serial_queue` with type `dispatch_queue_t` created by `dispatch_queue_create` is not released.
- The `CFStringRef` object created by `get_device_name` is not released
By the developer document about [`dispatch_queue_create`][dispatch_queue_create], `dispatch_release` could be saved with *ARC* (Automatic Reference Counting ?) support.
> If your app isn’t using ARC, you should call dispatch_release on a dispatch queue when it’s no longer needed.
However, it seems like we don't have *ARC* support now. From the resulte of *Instruments*, the `dispatch_queue_t` object created by `dispatch_queue_create` is leaked. Without *ARC* support, we should call `dispatch_release` explicitly. …
=> Fix memory leak

src/cubeb.c, src/cubeb_audiounit.cpp, test/test_device_changed_callback.cpp
If `state_callback` and `data_callback` are null, we will fail to call `stm->data_callback` and `stm->data_callback`. We call them without checking if they are not nulls. It seems to me that they are no options, so we should make sure they are properly set.
=> Make sure data_callback and state_callback are not null

CMakeLists.txt
Fixes build on aarch64.  We must've been picking ole32 up implicitly on x86 platforms.
FWIW: building on aarch64 requires CMake 3.10 or later and just requires passing "-A ARM64" when generating the MSVC projects.
=> Link ole32 in WASAPI backend for COM symbols.

src/cubeb_opensl.c
This allows supporting ancient Android versions.
=> Failing to set the input type on an input stream on OpenSL ES should not be fatal

src/cubeb_wasapi.cpp
Addressing crash in [1].
For the collection callback there are two object involved, the "notification client" which provides the callback and the "monitor" object that handles the thread and executes the user callback. The crash appears on the second object. The cubeb pointer there is null. The immediate problem I am observing is that monitor is created after the notification client. This patch will tie the two object together in order to have the same lifetime.
[1] https://crash-stats.mozilla.com/report/index/883c36f7-d02e-4b41-9377-0135b0190415
=> wasapi: tie monitor lifetime with notification client lifetime. BMO 1545279

src/cubeb_wasapi.cpp
The notification check did not include the disabled devices. We need that thought, especially with CubebDeviceEnumerator, because the cached list is wrong when a device becomes disabled.
=> wasapi: notify when a device is disabled. BMO 1546872

include/cubeb/cubeb.h, src/cubeb_wasapi.cpp
This has been merged in Gecko via BMO# 1427011 for quite some time.
=> wasapi: Add flag to disable default device switching.

src/cubeb_wasapi.cpp
clang warns about using `return std::move($LOCAL)`.
=> return unique_ptr normally, without std::move

CMakeLists.txt, src/cubeb.c
Add a configuration setting for the _Rust_ version of the _AudioUnit_ backend.
Some changes maded in cubeb.c has reviewed in [D23432][D23432], but the changes in  _CMakeLists.txt_ has not reviewed yet.
[D23432]: https://phabricator.services.mozilla.com/D23432
=> Add audiounit-rust backend

.travis.yml
Builds work fine but tests fail with 0xc0000135 (STATUS_DLL_NOT_FOUND) or hang (test_ring_buffer).
=> Enable Windows build on Travis.

src/cubeb.c, src/cubeb_pulse.c, tools/cubeb-test.cpp
A couple of simple fixes for -Wimplicit-int-conversion (available in Clang 8.0+).  ALSA, JACK, and AudioUnit backends were all clean.  Didn't test other build configurations.
cubeb_mixer.cpp has a bunch of warnings for this also, but it might be more involved to clean that up as it looks like it might be better to review the types used rather than just add checks and casts.
=> -Wimplicit-int-conversion warning fixes

src/cubeb_audiounit.cpp, tools/cubeb-test.cpp
Also lower the minimum latency, we'll see in gecko whether it can work.
=> Fix output latency reporting on OSX, and add a round trip latency testing mode to the tool

CMakeLists.txt
This fixes #480. I can't build on Linux without this.
=> Link pulse when building the rust pulse backend

src/cubeb_wasapi.cpp
Added code to get an `IAudioClient3` object, if possible, and then use `InitializeSharedAudioStream` when needed to get lower latencies.
WASAPI has some weird quirks which mean we can't always get the exact latency. It runs at a single, global (to the entire system) latency value. This means that if another client has already requested a specific latency, we have to match that. Additionally, requesting a latency value will also dynamically adjust every `IAudioClient` stream on the system to match.
All tests pass on Windows 10, and I tried it on a real-world project (Dolphin) as well. I'm not sure if there's anything special that needs to be done with duplex/loopback streams.
Quick overview:
- Tries to get an `IAudioClient3` object if possible, and uses `InitializeSharedAudioStream` to …
=> WASAPI: add support for IAudioClient3 and lower latencies on Windows 10

test/test_device_changed_callback.cpp
Bundled googeltest doesn't support death tests on any of BSDs.
https://github.com/google/googletest/blob/release-1.6.0/include/gtest/internal/gtest-port.h#L537-L546
=> Unbreak build on FreeBSD

CMakeLists.txt
Regressed by #539, see [dlopen(3)](http://man7.org/linux/man-pages/man3/dlopen.3.html). May require `-DUSE_SNDIO=ON -DUSE_ALSA=OFF -DUSE_JACK=OFF -DUSE_PULSE=OFF` to reproduce.
=> Add -ldl for USE_SNDIO as well

src/cubeb_alsa.c, src/cubeb_jack.cpp, src/cubeb_pulse.c, src/cubeb_sndio.c
Regressed by #539
- On Debian `.so` symlink is part of separate [`libasound2-dev`](https://packages.debian.org/sid/amd64/libasound2-dev/filelist) and [`libsndio-dev`](https://packages.debian.org/sid/amd64/libsndio-dev/filelist) packages
- On OpenBSD `.so.X` symlink is not provided because OS updates often change ABI of all libraries
- On rolling distributions runtime and development bits are not separate
=> Don't depend on development package for ALSA and SNDIO

src/cubeb_audiounit.cpp
A multiplication by the size of the type was missing.
This was not a problem, because apparently macOS clears the buffers, but when remoting this is not necessarily the case, and a glitch happens when draining.
=> Clear the buffer properly when draining.

src/cubeb_audiounit.cpp
This is right after the callback, that has the number of channels the
user requested, and can be different from the number of channels of the
device.
=> Use the number of channels of the stream, not the device, for draining computation.

src/cubeb_audiounit.cpp
This solves the deadlock mentioned in [BMO 1572273 comment 6][0]. It's very
likely to have a deadlock when the output callback tries to stop the
input AudioUnit when the input device is unplugged during the duplex
stream is working.
When the input device is unplugged, the stream will be reinitialized and
the AudioUnits will be stopped then. Hence we could only feed silence to
the output buffer and let stream reinit stop the AudioUnits.
[0]: https://bugzilla.mozilla.org/show_bug.cgi?id=1572273#c6
=> Avoid forming deadlock when steam drains upon device switching

src/cubeb_pulse.c
Clean up some leftover code that was only used via the panning API.
The cubeb-pulse-rs version already has this cleanup.
=> pulse: Remove unused sink_input_info_cb.

src/cubeb_jack.cpp
Since the JACK backend fakes the enumerate_devices API by returning two
"default" devices, we should also accept those "default" devices in
cbjack_stream_init if they're passed in via {input,output}_device.
Fixes https://github.com/kinetiknz/cubeb/issues/550
=> jack: Don't reject default {input,output}_device in cbjack_stream_init.

src/cubeb_pulse.c
Addresses [BMO 1582442](https://bugzilla.mozilla.org/show_bug.cgi?id=1582442).
=> pulse: Special case single channel center mapping to mono.

include/cubeb/cubeb.h
The example code provided in cubeb.h is quite useful when starting to use the library. It contained various errors though (variables were used before they were defined or not defined at all) and incorrect api usages. I guess cubeb has changed since the example was first written. 
This updates the example for the current version and fixes all errors so it can be compiled without changes.
=> Update example code

src/android/cubeb-output-latency.h, src/cubeb_opensl.c
A method for querying latency isn't strictly required, streams
work without it. But when no method could be loaded, this assertion
would be triggered when called from opensl_configure_playback.
=> Remove android latency assertion

src/cubeb_opensl.c
Float output is only available (and the code only be used) if the targeted android version at compile time as well as the device version at runtime is high enough (>= lollipop).
This PR does not add support for float capturing since i don't really care about that. Tested it with a >= lollipop device. 
BTW, would there be any interest in an AAudio backend for cubeb? Some of the OpenSLES stuff seems kinda messy to me and AAudio might improve performance.
=> Add support for float playback on android (OpenSLES)

src/cubeb_sndio.c
The first two commits fix two important memory issues.
* First commit allocates the size of `struct cubeb` instead of `struct cubeb *`, which previously would write beyond the allocated memory when assigning `libsndio` and `ops`.
* Second commit fixes writing beyond `struct pollfd[10]`, on my system 16 was required. It now uses `sio_ndfs` to avoid this from happening again.
The third commit is optional but imho improves the choice of which cubeb backend is used if libsndio.so is installed.
=> sndio backend fixes

.clang_complete, src/cubeb_resampler.cpp
For input-only streams or duplex streams on backends that always have as much input as output (this is the case for AAudio, i just split this change to a seperate PR), this eliminates a full data copy per callback.
=> Add passthrough resampler no-copy optimization

src/cubeb_sndio.c
Forcing cubeb to snd/0 is entirely inappropriate for FreeBSD where
using the sndio backend without a running sndiod is completely ok
and does not suffer from the same drawbacks (blocking the audio
device) as ALSA on Linux.
Using SIO_DEVANY (i.e., "default") will cause libsndio to open the
default device /dev/dsp on FreeBSD, so libsndio can be used without
running sndiod or extra configuration like setting the AUDIODEVICE
environment variable.
Regressed by a7b7cdbeeb79191fbf9c8dbe3934d9d1c5531067.
=> sndio: Always use SIO_DEVANY on FreeBSD/DragonFly

test/test_ring_buffer.cpp
See issue #567 for details.
@padenot, this retains (I think) the original intention, but the tests pass without `yield` too, so I'd be just as happy to remove it entirely.
=> test_ring_buffer: Use `yield` instead of `sleep_for(10us)`.

test/test_resampler.cpp
Fix the integer signed comparison mismatch in my last patch.
=> resampler: avoid integer signed comparison mismatch

src/cubeb_utils.cpp, test/test_loopback.cpp, tools/cubeb-test.cpp
Fixed a few warnings:
```
/home/travis/build/achronop/cubeb/src/cubeb_utils.cpp: In function ‘size_t cubeb_sample_size(cubeb_sample_format)’:
/home/travis/build/achronop/cubeb/src/cubeb_utils.cpp:23:1: warning: control reaches end of non-void function [-Wreturn-type]
}
```
```
/home/travis/build/achronop/cubeb/tools/cubeb-test.cpp: In member function ‘long int cubeb_client::user_data_cb(cubeb_stream*, void*, const void*, void*, long int)’:
/home/travis/build/achronop/cubeb/tools/cubeb-test.cpp:268:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (uint32_t i = 0; i < nframes; i++) {
^
/home/travis/build/achronop/cubeb/tools/cubeb-test.cpp:283:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (uint32_t i …
```
=> fix a few warnings

src/cubeb_wasapi.cpp
This merged in PR #530, but we had to disable it in Firefox due to the issues linked from https://bugzilla.mozilla.org/show_bug.cgi?id=1590902.
Rather than try to disable it on each import to Firefox, let's disable it upstream until we can resolve bug 1590902.
=> wasapi: Disable IAudioClient3 until BMO #1590902 is resolved.

src/cubeb.c
The mixer supports 32 input channels, so this is safe. This is necessary
for professional audio gear and for testing with virtual devices (in particular the new virtual audio device called [Blackhole](https://github.com/ExistentialAudio/BlackHole/) on OSX).
This also fixes [BMO#1610550](https://bugzilla.mozilla.org/show_bug.cgi?id=1610550).
=> Increase input channel count limit.

test/test_device_changed_callback.cpp
The *audiounit-rust* backend will return an error instead of hitting
an assertion when registering a second callback within
`cubeb_stream_register_device_changed_callback` without unregistering
the registered callback first. It's not possible to run a death test in *gtest*
for the Rust API[1], so the death test should not be used.
It's a regression of #481 . 
[1] https://users.rust-lang.org/t/how-to-write-a-death-test-in-gtest-for-rust-apis/23575
=> Remove test for registering device changed callback twice

src/cubeb_sun.c
The original implementation converted floats to 16-bit LPCM because that's what the sndio backend did, but it might be more desirable to leverage the NetBSD and illumos kernels' support for 32-bit LPCM instead.
=> sun: Convert floating-point audio to 32-bit LPCM instead of 16-bit LPCM before passing it to kernel

src/cubeb_log.h
This keeps the logging message consistent after djg/cubeb-rs#50 is merged, 
which fixes the [BMO 162132](https://bugzilla.mozilla.org/show_bug.cgi?id=1628132).
Instead of printing the full path to the file that is currently running,
we should print the filename only. As long as we have the filename and
the line, we know where the log comes from.
=> Only print the filename when logging

test/test_devices.cpp
This fixes the crash described in PR #440. The crash itself is a regression from commit 61aaac2, which causes the `CUBEB_ERROR_NOT_SUPPORTED` error code to be treated as if it was `CUBEB_OK`, resulting in a segfault when the test tries to access the collection structure.
=> tests: Fix crash when device enumeration is not supported

include/cubeb/cubeb.h, src/cubeb-internal.h, src/cubeb.c, src/cubeb_alsa.c, src/cubeb_audiotrack.c, src/cubeb_audiounit.cpp, src/cubeb_jack.cpp, src/cubeb_kai.c, src/cubeb_opensl.c, src/cubeb_pulse.c, src/cubeb_sun.c, src/cubeb_wasapi.cpp, src/cubeb_winmm.c
This is quite basic, only includes an implementation for windows (that I can't even compile, I'm getting a VM and will update this, the general idea is there).
An implementation for macOS is upcoming on `cubeb-coreaudio-rs`, and an update to `cubeb-rs` and associated crates is also coming since this adds a public method.
We need to take the resampling latency into account, which is not done at the moment, this will come after, I want to rework bits of this to have less latency, more control, and a more accurate reporting.
=> Add a method to get audio input latency on a stream

src/cubeb_opensl.c
Some GeckoView users don't want to output routing to be changed when an input stream of type voice is requested but would still like to use the correct mic. With this patch, we can request normal audio routing for output (`MUSIC` the default), while still telling Android that the input is a voice stream.
This helps fixing [BMO#1626081](https://bugzilla.mozilla.org/show_bug.cgi?id=1626081).
=> Allow setting the voice flag for input OR output, depending on the param struct that has the flag

src/cubeb_sun.c
Noticed when building with a newer clang version.
=> sun: Fix arithmetic on void pointer.

src/cubeb_wasapi.cpp
I forgot to `git add` this bit...
Doc is here: https://docs.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancefrequency (return value section).
=> QueryPerformanceCounter returns non-zero in case of success

tools/cubeb-test.cpp
It calls the stream ops and ask for input latency if the device
has type INPUT.
=> Add input stream latency test

src/cubeb_wasapi.cpp
For the same reasons we do it in other methods: it's possible that we've
not written enough frames to be greater than the latency.
=> Clamp stream_delay calculation to zero

src/cubeb_resampler_internal.h, test/test_resampler.cpp
Change the argument to int in order to prevent unsigned int overflow on the arithmetics bellow. An assert added to make sure that the argument has a valid value. Changed also the return type of `delay_line::input_needed_for_output` to be symmetric to the other one.
=> resampler: avoid overflow on uint arithmetics

src/cubeb.c
The change prefers using `audiounit-rust` backend. The rust backend is set as the default cubeb backend in *Firefox 74* and some new features have been implemented in the *Rust* backend only. Currently, the *Rust* backend is set by the `backend_name` via a preference in *gecko* when `cubeb_init` is called. With this change, the *Rust* backend will be set as the default cubeb backend if it exists, without passing the `"audiounit-rust"` to `cubeb_init`. 
Its related changes will be done in the [BMO 1598148](https://bugzilla.mozilla.org/show_bug.cgi?id=1598148).
=> Bump the priority of audiounit-rust in `default_init`

src/cubeb_sun.c
That's all to let it compile on a running OI-hipster 20200504.
=> sun: building fix in sun_stream_get_latency

src/cubeb_sun.c
=> sun: Fix use-after-free of s->mutex in sun_stream_destroy.

src/cubeb_resampler_internal.h, src/cubeb_wasapi.cpp
A series of loosely related fixes that improve duplex audio stream, in particular for bluetooth devices that support both A2DP and handsfree, to stop picking the A2DP device when using the mic, to have lower latency and more importantly because it seems like it doesn't work to have the mic in handsfree and the headphones themselves in A2DP (that would be weird anyways).
I'll add commits, because there is a problem with the resampling code (apparently a bad rounding that leads to premature draining of the stream), and I'm not sure yet about the default device matching policy. I might make it opt-in except when we know it makes sense (we might be able to detect that it's a bluetooth device, etc.). I'll also look at what other communication software do.
The review can start now, though, the …
=> Some windows fixes

src/cubeb_resampler_internal.h
This got found by the hazard job in Firefox's CI.
=> Fix printf format

src/cubeb_jack.cpp
Got pointed here from the Mozilla bug tracker to send in the patch upstream:
This is an attempt at a fix for [firefox bug 1614278](https://bugzilla.mozilla.org/show_bug.cgi?id=1614278) where firefox crashes on a regular on xruns. This has been a long standing issue for me (older than the linked bug report). With this patch applied firefox does run stable again with the jack backend.
Looking at the subtraction logic in the xrun handing I am somewhat surprised this does not crash more often. Might also be related to #154 
--
The number of xrun fragments to skip is added once to ctx->jack_xruns but
then subtracted multiple times (once for each stream) from the same variable.
This causes the unsigned int to "underflow" and wrap around.
- Use unsigned int in all calculations instead of mixing …
=> Fix integer underflow/unsigned wrapping.

src/cubeb_wasapi.cpp
Crash stack (from Gecko) is:
<details>
<pre>
mozglue.dll!arena_dalloc(void * aPtr, unsigned __int64 aOffset, arena_t * aArena) Line 3364	C++
[Inline Frame] mozglue.dll!BaseAllocator::free(void * aPtr) Line 4147	C++
[Inline Frame] mozglue.dll!Allocator<MozJemallocBase>::free(void * arg1) Line 54	C++
[Inline Frame] mozglue.dll!PageFree(const mozilla::Maybe<unsigned long long> & aArenaId, void * aPtr) Line 1280	C++
mozglue.dll!replace_free(void * aPtr) Line 1317	C++
[Inline Frame] xul.dll!operator delete[](void * ptr) Line 60	C++
[Inline Frame] xul.dll!`anonymous namespace'::wasapi_destroy_device(cubeb_device_info * device) Line 2998	C++
>	[Inline Frame] xul.dll!`anonymous namespace'::setup_wasapi_stream_one_side(cubeb_stream * stm, cubeb_stream_params * stream_params, const wchar_t * devid, …
=> Always return valid strings for `friendly_name` and `group_id` (sometimes empty)

test/test_sanity.cpp
This would have caught the mistake fixed by https://github.com/kinetiknz/cubeb/commit/a45f6d072f6e17e82a34769ef527f3041dca0259.
=> Add a test case for WASAPI reconfigure event

src/cubeb_jack.cpp
This brings the JACK backend into parity with e.g. the Pulse backend, which [has this behavior already](https://github.com/kinetiknz/cubeb/blob/master/src/cubeb_pulse.c#L580). A typical Firefox user [expects this behavior](https://bugzilla.mozilla.org/show_bug.cgi?id=979705), and because Firefox creates a new unique stream at every audio playback init it's difficult to achieve this behavior currently as a JACK user even if you know what you're doing. Other application users (of e.g. music or video players) will overwhelmingly have the same expectation. There may be esoteric cases in which strict 1 input <-> 1 output is desirable even if the source is mono, but if that case should be supported I think it should enabled via some sort of config rather than the default behavior.
I've tested …
=> jack: Output stereo audio if the input source is mono

CMakeLists.txt
This change fixes two things:
- Use `PROJECT_SOURCE_DIR` instead of `CMAKE_SOURCE_DIR` to use the `cubeb` directory instead of the root directory when the cmake project is included by another cmake project.
- Only build the rust version of pulse and audiounit backend if the C version of the backend was also going to be built.
=> Fix CMake rust path and only use rust deps if needed

include/cubeb/cubeb.h, src/cubeb-internal.h, src/cubeb.c, src/cubeb_alsa.c, src/cubeb_audiotrack.c, src/cubeb_audiounit.cpp, src/cubeb_jack.cpp, src/cubeb_kai.c, src/cubeb_opensl.c, src/cubeb_pulse.c, src/cubeb_sndio.c, src/cubeb_sun.c, src/cubeb_wasapi.cpp, src/cubeb_winmm.c, test/test_sanity.cpp
This PR adds a simple method called `cubeb_stream_set_name` to change a created stream's name so that bug 1120222 can be fixed. I'm new to C/CXX development, so there may be some mistakes.
=> Add method to change stream name

include/cubeb/cubeb.h, src/cubeb_wasapi.cpp
This is night and day in terms of quality on the XPS15 that I'm using, and I'm using the default setup, with the WAVES MaxxAudio app (required on this machine, otherwise, for example, plugging in a pair of analog headphones won't switch the audio output to those headphones). This app can be manually disabled, but otherwise inserts an APO that does noise reduction and echo cancellation, etc., but more importantly doubles ou triples the roundtrip latency.
Additionally, stacking echo cancellers and noise reduction is kind of wasteful.
I suppose we could make this a flag, to then make it controllable externally.
=>  Pass in AUDCLNT_STREAMOPTIONS_RAW when possible when initializing an AudioClient

include/cubeb/cubeb.h, src/cubeb_wasapi.cpp
Like #594 but as an optional thing.
This adds a stream preference flag to request a persistent audio session, so that volume and mute settings remain the same even after closing and reopening a program on Windows.
See https://docs.microsoft.com/en-us/windows/win32/coreaudio/audclnt-streamflags-xxx-constants for details.
=> Add stream preference to request a persistent stream session and implement this in WASAPI.

CMakeLists.txt, cmake/compile_tests/oss_is_v4.c, src/cubeb.c, src/cubeb_oss.c
This PR implements the OSS backend mainly targeting FreeBSD. The code was based on https://github.com/kinetiknz/cubeb/pull/510.
It has been tested on Illumos as well. (I didn't test the Illumos build with Firefox).
Real tests are done with FreeBSD Firefox build.
Playback is tested by playing YouTube musics.
Recording is tested with https://test.webrtc.org/ and the following project: https://higuma.github.io/web-audio-recorder-js/.
All tests passed except test/test_duplex.cpp.
```
Start  1: sanity
1/13 Test  #1: sanity ...........................   Passed   16.67 sec
Start  2: tone
2/13 Test  #2: tone .............................   Passed    0.59 sec
Start  3: audio
3/13 Test  #3: audio ............................   Passed   17.38 sec
Start  4: record
4/13 Test  #4: record …
```
=> OSS (FreeBSD/illumos) backend

src/cubeb_oss.c
This change is for the OSS backend based on the #615 . Since SNDCTL_GETSONG/SNDCTL_SETSONG isn't supported on FreeBSD now, I would leave the implementation empty instead.
=> Add method to change stream name for OSS backend

include/cubeb/cubeb.h, src/cubeb_jack.cpp
This patch adds a perf to disable auto jack port connection. This is useful if the user of the lib wants to coordinate connection management themselves, for example linking into a mixing app rather than straight to audio_out.
=> Add an option to not automatically connect ports on jack.

src/cubeb_resampler.cpp, src/cubeb_resampler_internal.h
cc @vitor-k
In #619, a patch is being rightfully reverted. I made this because it made cubeb stream with a user rate of 48000 and device rate of 44100 drain instantly, and it made sense at the time somehow, but I was fixing the symptoms and not the cause. This patch causes a drift, as reported in #619.
I'm adding another patch here on top of #619 to fix the initial problem while keeping the revert to unbreak the use-case discussed there. The issue in my particular use-case was that `input_needed_for_output` was asking the user callback for a number of audio frames that was too low, because it's subtracting the frames already buffered. But this is the beginning of the stream, so the number of already buffered frames should be zero, but is not, because we're adding latency frames at …
=> Revert "Don't account for unresampled data when computing how much input is needed." and fix the real problem

.travis.yml, CMakeLists.txt, include/cubeb/cubeb.h, src/cubeb.c, src/cubeb_aaudio.c, src/cubeb_aaudio.cpp, src/cubeb_log.h
This implements a first AAudio backend with support for input, output and duplex streams. It uses callbacks for best latency and is completely lock-free in the audio thread (as the aaudio docs recommend). I could only test it on one device. Some additional functions could be implemented via guesswork, jni or other APIs (see the SLES backend), I didn't do that for now and would prefer to keep this PR down to a first basic implementation. There are a couple of NOTEs in the code in places that could need improvements or at stuff I wasn't sure about. I will continue to fix out minor details but am already thankful for input, especially regarding the general backend design.
The cubeb docs don't state this so i assumed it's ok if the state callback is called from a different
thread than the …
=> Add AAudio backend

src/cubeb_aaudio.cpp, src/cubeb_android.h, src/cubeb_opensl.c
This is lots of little commits, implementing missing features that we have in the other Android backend, and other fixes.
With this patch set, the AAudio backend is at parity in terms of round-trip latency and resilience (if not better, depending on the device) compared to the OpenSL backend, on the same device. In a second phase, we'll be able to take advantage of AAudio-specific features or other recent Android audio things (such as unprocessed input streams, or using the hardware AEC).
In particular, it's interesting to note that we can trigger the `FAST_MIXER` fast paths in native code **without** having to do JNI madness or `dlopen`ing `libmedia.so`, but this requires opening a dummy stream.
The latency figures are fairly accurate, and I believe it's possible to make them very …
=> Bring the AAudio backend to parity with the OpenSL backend

.clang-format, src/cubeb_aaudio.cpp
I kind of tried something based on what I think the style is, but it's probably not finished and @kinetiknz will know best.
This is based on #622 but doesn't contain functional changes, https://github.com/kinetiknz/cubeb/commit/77c4812f89117c01944490ebd3aece9137075da1 has all the formatting changes.
=> Add a `clang-format` file and format `src/cubeb_aaudio.cpp`

src/cubeb_wasapi.cpp
An embarassing mistake, causing [BMO#1674283](https://bugzilla.mozilla.org/show_bug.cgi?id=1674283). I'm putting in a length check as well. `device_info.group_id` is guaranteed to be present.
=> Fix typo in handsfree tag

src/cubeb_wasapi.cpp
=> WASAPI: Adjust PCM format tag based on configured bits per sample

src/cubeb_jack.cpp
The previous patch to add an option to allow JACK clients not to be connected automatically was broken, not allowing autoconnect at all.
=> Fixed option to not automatically connect ports on jack.

src/cubeb_wasapi.cpp
This is a follow up to 5d5fa34e13f0bcf3356c7323e4ca800001675013.
Speculative fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1691425.
=> wasapi: Don't clear `device_enumerator` in {un,}register_notification_client.

include/cubeb/cubeb.h, src/cubeb-internal.h, src/cubeb.c, src/cubeb_aaudio.cpp, src/cubeb_alsa.c, src/cubeb_audiotrack.c, src/cubeb_audiounit.cpp, src/cubeb_jack.cpp, src/cubeb_kai.c, src/cubeb_opensl.c, src/cubeb_oss.c, src/cubeb_pulse.c, src/cubeb_sndio.c, src/cubeb_sun.c, src/cubeb_wasapi.cpp, src/cubeb_winmm.c, test/test_sanity.cpp
`cubeb_stream_reset_default_device` was a Windows-only hack added to work around a sandboxing restriction in Gecko content processes.  This is no longer an issue, so we can remove the API.
This is for https://bugzilla.mozilla.org/show_bug.cgi?id=1689517
=> Remove cubeb_stream_reset_default_device API.

src/cubeb_ringbuffer.h
https://en.cppreference.com/w/cpp/atomic/memory_order
`std::memory_order::memory_order_relaxed` has been renamed to `std::memory_order::relaxed` in c++20.
However, `std::memory_order_relaxed` has been added for backwards compatibility and is usable with both versions of the standard.
=> memory_order_relaxed has changed in c++20

src/cubeb_resampler.cpp
if input_frames_count is less than the minimum number of frames required to resample, resampled_frames_count will be zero, and the function will crash with a divide by zero.
For 44.1khz / 16khz, the ratio is 2.75 input samples to each resampled sample, so getting fewer than 3 samples means a crash.
See also https://github.com/mozilla/cubeb/issues/647
=> don't run resampler unless we have enough frames (fixes #647)

src/cubeb_wasapi.cpp
When connecting to a remote machine via Citrix, the devices on the remote machine exposes a _very_ small buffer size. This is too low for (e.g.) doing a WebRTC call with a robust audio input stream in Firefox. It's in fact not that much of a problem to increase the buffer size between `audiodg.exe` and cubeb, and makes the input a lot better. The buffer size itself doesn't affect latency that much, it's apparently something like a ring buffer that a bit bigger, so more robust on various under-runs, but latency is still kept quite low. I've tested this on the Citrix setup (where it improves the quality greatly), and on a couple local setups (where it seem to add a few milliseconds of latency maybe, but I'm not sure).
Also, `cubeb_wasapi.cpp` is currently grabbing the input data from the …
=> Fix audio input when the audio device is a citrix device

test/test_duplex.cpp
Add a test to check if we can open multiple input devices at the same time. This is a simple check when I debug an issue for [BMO 1238038](https://bugzilla.mozilla.org/show_bug.cgi?id=1238038). Everything works well on the cubeb end but I think it's no harm to add a test here. The duplex stream is to simulate the [duplex stream Firefox uses in GraphDriver](https://searchfox.org/mozilla-central/rev/290f33a3245f61f34ec5f80f548e6584823ba9ad/dom/media/GraphDriver.cpp#663). The input-only stream is used to simulate the second microphone we will open.
=> Add a multiple input devices test

src/cubeb_wasapi.cpp
=> wasapi: Avoid a few copies in `wasapi_find_matching_output_device`.

test/test_sanity.cpp, test/test_tone.cpp
Turns out it was testing the preroll, and with it gone from the
pulse-rust backend in https://github.com/mozilla/cubeb-pulse-rs/pull/69,
this fails on (at least) docker-on-AWS hosts on Mozilla's infra.
Also, lots of tests fail for me locally on the latest Ubuntu LTS, but I'm not really sure why, it seems to deadlock on the main loop lock when doing lots of start/stop operations in a short period of time.
5000ms seem to work on the test boxes though, they are really slow to start (1000ms doesn't work consistently for example).
=> Increase delay to really test the pulse backends

.github/workflows/build.yml, CMakeLists.txt
Adds a new `check_format` job using a new `clang-format-check`  (non-default) CMake target.  This job only runs on Linux, but it checks all files.
=> Add clang-format-check target to CMake and run on CI.

src/cubeb-jni.cpp
Clang format reorders the headers and created compile error. I also turned off clang-format here from now on
=> android: Fix build error

CMakeLists.txt
This makes the shared library usable when installed system-wide.
`cubeb_VERSION` and `cubeb_VERSION_MAJOR` are set when calling `project(cubeb VERSION x.y.z)`
=> build(cmake): add version and soversion to the built library

CMakeLists.txt
Users can now disable the lazy loading of libraries, and use classic linkage instead
From #662
=> build: add LAZY_LOAD_LIBS option and always link with threads

src/cubeb_aaudio.cpp, src/cubeb_alsa.c, src/cubeb_jack.cpp, src/cubeb_pulse.c, src/cubeb_sndio.c
As discussed in PR 665 [here](https://github.com/mozilla/cubeb/pull/665#discussion_r742502079), the definition of `WRAP` is incorrect and exposes the wrapping abstraction for non-function-pointer symbols.
=> Tidy up `WRAP` definition for dlopen.

src/cubeb_oss.c
The change is to reduce the number of dropped frames when playing
YouTube videos.  The most significant part is to set trigger threshold
to be low enough, such that as long as the audio hardware's DMA engine
moves data the callback is triggered without waiting longer.  Besides
that, unify oss_wait_*fd_for_space() for both directions into a single
function.  Buffer size is also not required to match the other
direction.
Sponsored by:	The FreeBSD Foundation
=> cubeb_oss: changes to buffering logic

src/cubeb_oss.c
There are some warnings that I did not catch (for no reason, or some reasons I did not recall).
=> OSS: Fix warnings in the initialization path

src/cubeb_oss.c
This is a patch from @hselasky . To calculate maximum buffer size, use bi.fragstotal instead of bi.fragments since bi.fragments is usually zero for recording direction.
=> cubeb_oss: Fix recording buffer size computation.

src/cubeb_wasapi.cpp
Locally (on a i9-9900KS with ~60 input/~60 output devices), this reduces a single enumerate_devices call from ~1100ms to ~250ms.
=> wasapi: Speed up enumerate_devices by caching default device IDs for each flow/role instead of requerying for every wasapi_create_device.

src/cubeb_oss.c
Also when the latency is specified to be very big.
This might be a bug in some upper layer, although I see
other cubeb audio drivers doing the same.
This "fixes" audio sync with youtube videos.
=> cubeb_oss: Force at maximum 32ms service intervals.

CMakeLists.txt
Some systems offer OSS v4 but do not have BSD-only functions like `strlcpy`, used in cubeb_oss.c. An example is Debian GNU/kFreeBSD, that uses a FreeBSD kernel with GNU userspace utilities, like glibc.
With this patch cubeb will be able to build on these systems thanks to the help of libbsd, that privides most libc functions that you would expect on BSDs.
~Please note that I did not test this patch yet, but I'll do it as soon as possible.~
=> build: use libbsd when using OSS and glibc

src/cubeb_wasapi.cpp
Avoids potential racy mutation of `context->device_ids` and other fields.
=> wasapi: Protect access to cubeb context members.

src/cubeb_utils_win.h
[SRWLocks](https://docs.microsoft.com/en-us/windows/win32/sync/slim-reader-writer--srw--locks), available since Windows 7, are lighter weight and cheaper (at least in uncontended cases) than CRITICAL_SECTIONS.
=> owned_critical_section: Replace CRITICAL_SECTION with SRWLOCK on Windows.

src/cubeb_aaudio.cpp, src/cubeb_audiounit.cpp, src/cubeb_jack.cpp, src/cubeb_opensl.c, src/cubeb_resampler.cpp, src/cubeb_resampler.h, src/cubeb_resampler_internal.h, src/cubeb_wasapi.cpp, test/test_resampler.cpp
This does nothing for now. This is the first change of a multipart change across `libcubeb`, `cubeb-rs`, `cubeb-coreaudio-rs`, `cubeb-pulseaudio-rs`, but it changes ABI, so I'm splitting it out.
=> Add a parameter to cubeb_resampler_create to enable reclocking

src/cubeb_wasapi.cpp
This PR avoids calling API when we don't really need it, and avoid overwriting `input_bluetooth_handsfree` during setting output side.
=> Avoid unnecessary API calls when initializing a stream

src/cubeb_wasapi.cpp
We should not always reset the device when the current device is unplugged. The device reset or not should follow the `CUBEB_STREAM_PREF_DISABLE_DEVICE_SWITCHING` pref.
=> Don't reset device if CUBEB_STREAM_PREF_DISABLE_DEVICE_SWITCHING is set

src/cubeb_wasapi.cpp
We should not switch device behind the scenes if the user asks to use a particular device. If the user-selected device is unavailable, we should fire an error callback to notify the user so they can take the actions by their needs.
=> Switch device only when the users don't specifiy a particular device

src/cubeb_wasapi.cpp
- bb2721e996e1ead9c3f7c6da100b54d50422e617: Excludes non-user-visible devices (DEVICE_STATE_NOTPRESENT) from the device list
- 5a5d6fc2026b276b1d6b8922a5019df50c10131f: Query only active devices when matching BT output device to BT input device
=> wasapi: Reduce device enumeration cost by excluding unnecessary devices

src/cubeb_wasapi.cpp
Stop audio clients when the render thread exits, since we're no longer servicing events on the associated event handles and leaving the clients running when we're not servicing events on them is a waste of system resources (and triggers avoidable underruns in the OS audio server).
Closes https://github.com/mozilla/cubeb/issues/366
=> wasapi: Stop audio clients when render thread exits.

src/cubeb_wasapi.cpp
Follow up to https://github.com/mozilla/cubeb/pull/695#discussion_r832770698.  Before that PR, we would fail setup when GetDevicePeriod failed.  This restores that behaviour by verifying `latency_hi` is valid.
This fixes [BMO 1764394](https://bugzilla.mozilla.org/show_bug.cgi?id=1764394).
=> wasapi: Fail stream setup instead of asserting if device latency unavailable.

.github/workflows/build.yml
- https://github.com/actions/virtual-environments/issues/5583
=> CI: update actions to v3, use macos-11 environment and bump Android API target

src/cubeb_ringbuffer.h
The index loads are over-optimistically relaxed, so I changed them to the right ones.
=> fix synchronization mistakes in ring buffer

INSTALL.md
Changes in the instructions:
- Use cmake version 3.14 as minimum (required as per `CMakeLists.txt`).
- Build inside a `./build/` directory instead of a parent directory, as it is usual in cmake projects (and it is already in `.gitignore`).
- Use `cmake -B`.
Note: we could also change `cd build && ctest` to `ctest --test-dir ./build` but that requires cmake v3.20+.
=> Update build instructions

src/cubeb_log.cpp, src/cubeb_tracing.h
The purpose of this header is to be swapped by cubeb users to use any number of frame profiler (tracy/Gecko Profiler/trace_event.h, etc.).
It's likely that this will get a bit more sophisticated in the future, if we don't switch to rust tracing facilities first. I mostly need the thread registration for now.
=> Add a header to be able to use a frame profiler in cubeb

src/cubeb_resampler_internal.h
I need this to debug something in the field, now that we're close to having a way to easily getting logs.
=>  Add logging statement when input audio dropping happens 

src/cubeb.c, src/cubeb_log.cpp, src/cubeb_log.h, src/cubeb_pulse.c
It's useful to be able to enable logging dynamically while the program is running, and this can now be done on any thread.
Various threads are logging (directly or asynchronously via the ring buffer), it's better to have those atomic.
Both values are always checked before logging, and both must be non-null to log.
=> Make the log callback and level atomic

src/cubeb_alsa.c, src/cubeb_oss.c, src/cubeb_sndio.c, src/cubeb_sun.c, src/cubeb_wasapi.cpp
This covers some callbacks, but not all of them: the APIs that don't require explicitely creating the thread will see their thread registered separately.
=> Register threads explicitely created by cubeb

CMakeLists.txt, src/cubeb.c, src/cubeb_log.cpp, test/test_logging.cpp
When logging asynchrously, there's ample time for the pointer to be nulled.
=> Null check g_cubeb_log_callback before using

src/cubeb_wasapi.cpp, tools/cubeb-test.cpp
Default output devices changes may call `OnDefaultDeviceChanged` multiple times during a single real device change event.  Ignoring changes that don't match `eRender` or the notification client's configured role reduces this somewhat, but it seem useful to debounce device changes even when they do match the flow and role of the stream if they arrive closely together and the new `device_id` is the same as the previously seen one.  Chromium does something similar, so I've taken inspiration from that code and used the same debounce timer (250ms).
=> wasapi: Avoid reconfiguring default output stream spuriously.

src/cubeb_log.cpp, test/test_logging.cpp
Turns out the previous code wasn't safe.
Here I'm using `compare_exchange` to grab the queue exclusively (swapping with a `nullptr`) when pushing a message, in a way that it can't be deallocated.
When deallocating, the thread that wants to do so first waits for the consumer thread to stop, by joining, and then synchronizes with the real-time audio thread by grabbing the queue itself (same way, by setting to `nullptr`). At this point, the real-time audio thread starts dropping the messages on the floor (or has already observered that logging has been disabled, so doesn't log).
We can then proceed with the deallocation.
I've added a stress-test that has found a bunch of issues while running for longs periods of time, and now runs without issues under ASAN and TSAN, on x86_64.
=> Allow the asynchronous logging system to safely delete its storage

CMakeLists.txt, src/cubeb_aaudio.cpp, src/cubeb_triple_buffer.h, test/test_triple_buffer.cpp
I'm going to add commits for the input-only and duplex case later, since this also provides the latencies we need there, but it's going to be more or less the same.
@kinetiknz, with this, I believe we can attempt to reenable AAudio in Firefox.
I've attempted to fix the latency reporting in the OpenSL backend, without much success, but maybe it's doable as well. AAudio's API is a lot clearer.
The latency computation part is essentially what is done [in Oboe](https://github.com/google/oboe/blob/03db05df380486643bcf02eab9b3f1350b8069ad/src/aaudio/AudioStreamAAudio.cpp#L682), written by the Android audio people, so it should be correct.
A/V sync and clock resolution look perfect on my device, with all audio devices I checked.
=> Implement client-side clock interpolation for the AAudio backend, and accurately compute audio latencies

src/cubeb_wasapi.cpp
Address a UAF caused by `auto_lock` writing to the lock address (which is owned by `context`) when the destructor runs.
=> wasapi: Drop context lock before deleting context.

src/cubeb_jack.cpp
Jack works under NetBSD.
Enable strdup(3) for NetBSD like FreeBSD to fix build.
=> Support jack under NetBSD

src/cubeb.c
The last issues have been fixed, and it's now better (and also uses an API that isn't deprecated).
This falls back to OpenSL ES on older devices.
=> Prefer the AAudio backend over the OpenSL ES backend

CMakeLists.txt
This will cause an error about too few arguments to REPLACE if it's empty.
=> cmake: quote CXX_FLAGS substitution for MSVC

CMakeLists.txt
The android ndk has a quite strict policy concerning symbols that are not defined with the specified API level: referencing them is not allowed and causes the compiler (not even the linker) to return an error. Cubeb only uses the decltype of these symbols, which shouldn't even matter for the linker, but this is enough for the build to fail.
You can see the result here when lowering the API level to 24 [https://github.com/Macdu/cubeb/actions/runs/4023956553/jobs/6915428069](https://github.com/Macdu/cubeb/actions/runs/4023956553/jobs/6915428069) (aaudio is only available for API >= 28). It is therefore not possible to build cubeb for a low API level and then dynamically load aaudio if it is available.
A way to prevent this is to define the `__ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__` …
=> cmake: Make undefined symbols weak on Android

src/cubeb_alsa.c
On NetBSD, timersub() macro is defined only in _NETBSD_SOURCE block of sys/time.h.
Please define _NETBSD_SOURCE for NetBSD.
=> On NetBSD, define _NETBSD_SOURCE for timersub()

src/cubeb_opensl.c
Based on examining crash dumps and investigating OpenSL workarounds in liboboe, there is a potential race between active buffer callbacks and stream shutdown, resulting in a buffer callback attempting to use a new buffer after stream destroy has freed the backing allocation.
Ideally there would be a concrete event to watch for to ensure the last callbacks have completed before destroying the stream, but I'm not aware of one and the existing workaround in liboboe relies on an arbitrary ("long enough") sleep between stopping and destroying streams 😞.
=> opensl: Attempt to avoid a race with active callbacks during shutdown.

src/cubeb_aaudio.cpp
This BMO bug was random crashes during calls, mostly when using a bluetooth device.
The cause of this bug was because when an error happened, the backend didn't wait for the streams to be stopped before firing the state callback.
`AAudioStream_requestStop` simply requests the stream to stop (as the name implies), and the buffers are flushes before the stream stops. If the stream is outputing to a bluetooth device, the long buffer makes it more likely for a data callback to fire, apparently, and we were in a situation where the cubeb user thought the stream was in error, but a data callback was fired after the error callback being called. In practice, Firefox's recovery logic had kicked in, and the data callback was calling at the same time into the graph as some other code, wrecking …
=> Fix BMO#1824469 - Wait for the streams to be stopped before firing the state callback when an error occurs, in cubeb_aaudio.cpp

.github/workflows/build.yml
A typo made after the [previous update](https://github.com/mozilla/cubeb/commit/3dd0c44a39a95ef967ae1e919034ff675dd36da8) and discovered only now.
=> Re-enable the test job on macOS CI

src/cubeb_aaudio.cpp
See https://crash-stats.mozilla.org/report/index/335dbfcd-f97d-4aaa-9fb7-10a300230802
=> AAudio: Don't unlock a mutex owned by a lock_guard

src/cubeb_aaudio.cpp
This is not great because it can allocate from the callback (only once or twice, so it's fine) but we need something we can uplift: we're trashing some memory and this is crashing in various locations in gecko.
=> AAudio: ensure input buffer is large enough when reading input data

test/test_duplex.cpp
The break removed here makes sense for input-only, where breaking has no side effects. In a loopback duplex case like here it makes the callback exit early, before having written all frames. This can be caused by clipping on the input side (as observed on MacOS) and creates a distortion that sounds terrible.
=> In test_duplex loop back all input frames

src/cubeb_aaudio.cpp, src/cubeb_opensl.cpp
This series does the following:
- fixes a bug on OpenSL (classic confusion audio sample vs. audio frame)
- fixes a crash about logging in OpenSL and AAudio backend (this isn't very good but works well for what we need)
- fixes an issue in which cubeb errored out when attempting to read from an input device that was disconnected: this happened when opening a Bluetooth input that was changing protocol or something like that. This is largely the same logic as other backends: device disconnected -> reinit
- make it so `latency_frames` is the buffer size that will be passed to the callback, allowing aligning buffer size in the entire processing chain, yielding improved performance
- increase the buffer size to be 3 times the burst size (triple buffering), this seems to behave appropriately, …
=> Assorted Android fixes

src/cubeb_utils.h
cubeb-coreaudio-rs has hit a case when running its tests on MacOS 12 where it fails the `assert(destination && source);` in `PodCopy` because it tried to push 0 samples to an auto_array of length 0, as the internal auto_array buffer had not been allocated yet.
=> auto_array: protect from various calls when length_ is 0

include/cubeb/cubeb.h, src/cubeb.c
Bug 1877319 is caused by someone using a sound card running at 384kHz. It's the max I've seen in products online.
=> 384kHz ought to be enough for anybody

src/cubeb.c
Clients may want to disable processing...
=> Allow setting CUBEB_INPUT_PROCESSING_PARAM_NONE

CMakeLists.txt, src/cubeb_wasapi.cpp
Turns out this can crash sometimes, and we need to be more careful. cc @yjugl.
This reverts commit 661c653c8650b2b1c485e86b5a5b4f6d0ed07d1b.
=> Restore using thread priority facilities via function pointers

.github/workflows/build.yml
- According to the [roadmap](https://github.com/actions/runner-images/issues/9255) all pre macos-13 VMs will be removed by Q4 2024.
- Enable Dependabot to track changes to the CI configuration.
=> Update GitHub Actions macOS builders

src/cubeb_aaudio.cpp
This fixes #767.
@liamwhite if you want to give this one a quick test drive. Or maybe explain to me how to trigger it -- maybe I just got lucky in my testing and didn't hit it, or just blamed what was really a timeout on something else since I had so many half-baked changes on this backend when making modifications recently.
=> Handle `AAUDIO_ERROR_TIMEOUT` both in and outside the real-time thread

CMakeLists.txt, src/cubeb_audio_dump.cpp, src/cubeb_audio_dump.h, test/test_audio_dump.cpp
I'll expose this to rust next. Example usage in `test_audio_dump.cpp`.
This is going to be quite useful to diagnose exactly what comes out of the system level callbacks, and compare to what is resampled and delivered at the application level, etc.
@Pehrsons
=> Add internal utility to log audio streams to disk from real-time audio callbacks

src/cubeb_aaudio.cpp, src/cubeb_triple_buffer.h, test/test_triple_buffer.cpp
`aaudio_stream_get_position()` returns incorrect result because `aaudio_stream_init()` recycled destroyed stream where the `timing_info` buffers contain stale data.
=> Invalidate timing info buffers when destorying AAudio stream.

.github/workflows/build.yml, src/cubeb_aaudio.cpp
Diagnosed by jolin@mozilla.com, the same code is also found in Chromium.
@jhlin r? (I'm not sure how to flag you as reviewer on GitHub).
=> Clamp to positive value when computing latency for an output stream

src/cubeb_opensl.cpp
LLVM's libc++ is removing transitive inclusions among std header files in newer C++ versions, so user code must explicitly include needed std header files. In this case, cubeb_opensl.cpp must explicitly include <memory> for `std::unique_ptr` because, starting in C++23, <vector> no longers includes <memory>.
https://libcxx.llvm.org/DesignDocs/HeaderRemovalPolicy.html
```
libcubeb/src/cubeb_opensl.cpp:140:8: error: no template named 'unique_ptr' in namespace 'std'
140 |   std::unique_ptr<cubeb_stream_params> input_params;
|   ~~~~~^
```
=> Include <memory> for std::unique_ptr

src/cubeb_aaudio.cpp
This helps avoid underruns in input/duplex streams.
=> Set buffer capacity to allow for buffering

src/cubeb_aaudio.cpp
Without a reset, a duplex stream being reused as an output stream will open an input stream and provide an input buffer, which is not expected.
=> Reset stream params on init

src/cubeb_aaudio.cpp
If a stream has previously been stopped and then started, the elapsed time in between should not be included when calculating the position.
Also, `AAudioStream_requestStop()` doesn't behave as expected.
=> AAudio: don't count the time of stopped stream and replace stop request with pause. 

src/cubeb_aaudio.cpp
When reinitializating (due to output device change), `cubeb_stream::previous_clock` isn't reset properly but stream gets reset and restarts `AAudioTimingInfo::output_frame_index` from zero. Therefore, `aaudio_stream_get_position()` always reports previous clock rather than actual position until it is surpassed later. (See [Gecko bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1902263).)
This patch:
- renames `position_interpolator` to `position_estimate` for the additional responsibility.
- gets the number of frames sent to stream before it's destroyed and saves the value to `position_estimate` as the basis for future position estimation.
=> AAudio: offset position after reinitialization

src/cubeb_opensl.cpp
Add some extra asserts to help track down [BMO 1913284](https://bugzilla.mozilla.org/show_bug.cgi?id=1913284).
Also switch from `assert()` to our `XASSERT()` wrapper so we go through Gecko's assert machinery to have crash reports annotated with the failing assert text.
=>  opensl: Add extra asserts to help track down BMO 1913284. 

src/cubeb_wasapi.cpp
Prior to https://github.com/mozilla/cubeb/pull/682, a device could be default for all of
MULTIMEDIA, NOTIFICATION, and VOICE.
After that PR, the first two were mutually exclusive with the third, I
believe unintentionally.
Restore this behavior so that, e.g., on devices with only one output device,
querying for the "voice" device returns that device.
=> wasapi: Fix default device handling.

CMakeLists.txt
If building with debug, also build standard libraries with debug. This ensures that any libraries linking against cubeb won't have mismatched symbol definitions.
=> windows: Set debug options if appropriate.

.gitmodules
Per https://github.com/mozilla/cubeb/wiki/Backend-Support the rust backends for pulse and coreaudio are tier-1 and the older C++ backends are tier-4. So, add these backends to cubeb by default.
I can also set BUILD_RUST_LIBS to ON by default in this PR, but I'm not sure if there's some reason to avoid doing that.
=> Add submodules for tier-1 rust backends.

CMakeLists.txt
Also, use gecko-in-tree feature to break circular dependency.
=> Update rust submodules.

CMakeLists.txt
This pull request corrects for an issue introduced in 877364f0509c9a54f2d7015a6a9b52b4c7c99edc which caused anything dynamically linking against cubeb to fail to compile via MSVC due to a mismatched `RuntimeLibrary` value. There was no clean way to fix this issue in the dependent project due to there being no cmake configuration option to prevent this value from being set.
The pull request fixes this by adding a new `USE_STATIC_MSVC_RUNTIME` option which, when enabled, sets `CMAKE_MSVC_RUNTIME_LIBRARY` to `MultiThreaded$<$<CONFIG:Debug>:Debug>`.
If the option is not set, `CMAKE_MSVC_RUNTIME_LIBRARY` will be left at its default value, which [as per the cmake documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html) is …
=> Add `USE_STATIC_MSVC_RUNTIME` cmake option instead of always using statically-linked runtime library

src/cubeb_aaudio.cpp
This is a fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1936675.
=> On reinit, only call AAudioStream_getFramesWritten on a real stream

src/cubeb_wasapi.cpp
This was a workaround for rare pre-Windows 10 systems where the render thread would hang inside OS API calls for multiple seconds.
=> wasapi: Remove thread shutdown timeout.

test/test_resampler.cpp
@karlt this is needed because of https://treeherder.mozilla.org/jobs?repo=try&revision=90f1590f80f89d11c7517c7a0d50217d46d28eae. It is functionally equivalent.
=> Use less modern C++ so that it compiles in Firefox

include/cubeb/cubeb.h, src/cubeb.c
This was initially added in https://github.com/PCSX2/pcsx2/pull/7102 to facilitate dynamic audio selection. It's also used in duckstation for the same reason.
=> Add cubeb_get_backend_names

src/cubeb_log.cpp
test/test_logging.cpp should already verify the case of turning logging between verbose and off in the `logging` test and `logging_stress` flips between disabled and normal.
=> Only start log thread if using CUBEB_LOG_VERBOSE.
