mozilla/cubeb

src/cubeb-internal.h
src/cubeb.c
src/cubeb_alsa.c
src/cubeb_audiotrack.c
src/cubeb_audiounit.c
src/cubeb_jack.cpp
src/cubeb_kai.c
src/cubeb_opensl.c
src/cubeb_pulse.c
src/cubeb_sndio.c
src/cubeb_wasapi.cpp
src/cubeb_winmm.c

I'm probably doing this wrong....

Device notification for PulseAudio

---

src/cubeb_pulse.c

Add missing mutex protection to methods that communicate with PulseAudio thread. The methods are 
- pulse_enumerate_devices
- pulse_register_device_collection_changed
The problem reproduced by firing a number of threads that call the methods.

Pulse: Add missing synchronizations

---

src/cubeb_audioqueue.c

The PR contains the changes in audioqueue back end due to resent interfaces changes.

Interface changes for audioqueue

---

src/cubeb_wasapi.cpp
test/test_duplex.cpp

With the resampler bits landed, this is rather straightforward to implement.

Implement input and duplex streams in the WASAPI backend.

---

src/cubeb_sndio.c

Cf https://bugzilla.mozilla.org/show_bug.cgi?id=1153179 & https://bugzilla.mozilla.org/show_bug.cgi?id=1153151, unbitrotted.

Bug 1153151 1153179

---

src/cubeb_resampler.cpp
src/cubeb_resampler_internal.h
test/test_resampler.cpp

Those are fixes for the resampler patches, although I still need to write regression tests.

Resampler fixes

---

src/cubeb_audiounit.c

Correct one error and some warning found during building/testing with gecko. Also added some log messages helping to follow the flow during debug executions.

Gecko errors and warnings

---

src/cubeb_resampler.cpp
src/cubeb_resampler_internal.h
src/cubeb_wasapi.cpp
test/test_duplex.cpp
test/test_resampler.cpp

Getting there, it's almost green.

More small fixes for the resampler and wasapi code

---

src/cubeb_audiounit.c

This correct an error create during merging the gecko version of the file to cubeb repo.

Correct error due to wrong merge

---

src/cubeb_resampler.cpp
src/cubeb_resampler_internal.h
src/cubeb_wasapi.cpp
test/test_resampler.cpp

Mostly warning as error and asserts.

More little fixes

---

src/cubeb_wasapi.cpp

Allow to use device selection to create a stream with WASAPI.

---

test/test_sanity.cpp

Signed-off-by: Damien Zammit <damien@zamaudio.com>

test_sanity: Fix for zeroing buffers of correct type

---

src/cubeb_jack.cpp

Signed-off-by: Damien Zammit <damien@zamaudio.com>

Add duplex JACK backend

---

test/test_latency.cpp
test/test_sanity.cpp

Two small fixes on tests to make them compile and pass under Android native environment.

Test fixes for opensl

---

src/cubeb_audiounit.c

Stop triggering user callback right after `cubeb_stream_stop` is called even if IO threads do not stop immediately. 
This cause a assert crash on gecko on debug mode when audio device operates on high rate (48000).

Set shutdown flag on stop

---

src/cubeb_opensl.c

Correct build errors found during try run https://treeherder.mozilla.org/#/jobs?repo=try&revision=7327dff1cce9

Correct build errors with latency in frames

---

src/cubeb_audiounit.cpp

Clamp OSX latency up and down to work around getting weird number on mozilla test slaves

---

src/cubeb_audiounit.cpp

This tests _all_ system and print info about the failure.
@achronop, can you have a look ?

Improve logging in the AudioUnit backend.

---

src/cubeb_audiounit.cpp

Create redefine limit and clamp latency inside. If more than one stream is initialized limits only lower values of latency are allowed.

Clamp latency inside pre-defined limits

---

src/cubeb_audiounit.cpp
src/cubeb_utils_unix.h
src/cubeb_utils_win.h

Fix build errors found on try builds.
@padenot can you please review ?

Fix gecko build errors

---

src/cubeb_pulse.c

In case of stop during drain wait for the pa_time_event to timeout before stop the stream. Solves the problem described in issue #147

pulse: Wait to drain if stop during draining

---

include/cubeb/cubeb.h
src/cubeb-internal.h
src/cubeb.c
src/cubeb_audiounit.cpp
src/cubeb_log.h
src/cubeb_pulse.c
src/cubeb_wasapi.cpp

This implements more or less what was in the issue, but I decided against putting things on the context, and rely on global instead, it's better for ergonomics.

External logging

---

src/cubeb_wasapi.cpp

The long-term plan is to implement the device change callback and to be able to disable only a side of the stream, but this prevent locking everything up without informing the user.
If we can't open the device because it's been invalidated, we simply retry with the default device.

Fallback to a the default device if the current device has been invalidated, when opening a stream

---

src/cubeb_audiounit.cpp

@achronop, can you take a look ?

Check the format of the input stream using & and not ==.

---

src/cubeb.c
src/cubeb_audiounit.cpp

#176 got merge a bit too early it seems. @kinetiknz, does that look better?

Address #176 comments

---

.travis.yml
src/cubeb_audiounit.cpp

Same concept as PR #192, but for the AudioUnit backend.
r? @padenot or @achronop

audiounit: First pass at using modern C++.

---

src/cubeb_mixer.h
src/cubeb_pulse.c

- Convert ```cubeb_channel_layout``` to ```pa_channel_map```
- Set ```pa_channel_map``` in ```pa_stream_new```
- Add ```pulse_get_preferred_channel_layout```
- Convert ```pa_channel_map``` to ```cubeb_channel_layout```

Multiple channel support on Linux

---

src/cubeb_audiounit.cpp

A small patch to fix a code unreachable warning.

audiounit: Fix code unreachable warning

---

src/cubeb_wasapi.cpp

We use the same strategy on OSX. Testing locally with a setup where I could repro a drift after some time, this fixes it: no drift in 18 hours (I let it run overnight).
The plan is to come up with a full-fledged drift compensation mechanism, but it's not finished, and this does the trick for now.

Stop inserting silence when we don't have input data and need to render some audio, on Windows

---

src/cubeb_audiounit.cpp
src/cubeb_resampler.cpp
test/test_resampler.cpp

Resolve more drift scenarios. This patch is complementary to the previous one - 581d4bc

audiounit: additional fix for drift cases

---

src/cubeb_audiounit.cpp

The patch addresses the follow up comments of PR #231

audiounit: aggregate devices follow up

---

src/cubeb_pulse.c

pa_context_get_server_info and pa_context_get_sink_info_by_name both return
pa_operations, which require the caller to unref them.  In both cases we
were ignoring the return value and leaking the operations.
@djg This also fixes the missing wait that you noticed when porting to Rust.

pulse: unref pa_operation in two places where their return was ignored.

---

src/cubeb_audiounit.cpp
test/test_mixer.cpp
test/test_tone.cpp

- Fix following issue with #274
- Use auto-for-loop in ```text_mixer.cpp```
- Rename mixer stuff in ```cubeb_audiounit.cpp```

some cleanup

---

src/cubeb_audiounit.cpp

In `audiounit_reinit_stream()` local variable `was_running` was out of sync when a stream_start/stop was being raised at the middle of the method execution. Now reinit reads the `shutdown` flag directly.

audiounit: synchronize reinit and start/stop stream

---

src/cubeb_pulse.c
test/test_record.cpp

In pulse audio backend allow UNDEFINED as layout for recording.

Pulse layout assert

---

src/cubeb_audiounit.cpp

I found by testing that (un)register system listeners (AudioObjectID = kAudioObjectSystemObject) are prone to deadlock. During reinit there is no point to re-register those listeners since they are referring to global audio id. This patch extras the system listeners to a separate method which is called only in stream init/destroy.

audiounit: Stop re-register system listeners on reinit to avoid deadlock

---

src/cubeb.c
test/test_devices.cpp

Allow passing invalid cubeb_device_collection structure to cubeb_device_collection_destroy().

Destroy invalid collections

---

src/cubeb_audiounit.cpp

I noticed by testing that if the system dispatch queue (with name com.apple.audio.CADispatchQueue.SerialQueue) get delayed there is bigger likelihood to get a CoreAudio deadlock on one of the stages of reinit (which happen in the custom queue with name org.mozilla.cubeb). I am able to repro the deadlock if I sleep in the corresponding process while the stream mutex is locked. In order to avoid that I avoid to use the stream mutex inside the property listener callback. In addition I removed the use of stream lock from get position method since it is not needed (cubeb_stream::frames_played is an atomic) and blocks the MediaPlayback thread. 
Try run (in progress):
https://treeherder.mozilla.org/#/jobs?repo=try&revision=4960c690f186807f453c4211a13c7ee37306df56

audiounit: remove stream lock from property listener and get position (Bug 1335512)

---

include/cubeb/cubeb.h
src/cubeb.c
test/test_duplex.cpp
test/test_latency.cpp
test/test_overload_callback.cpp
test/test_sanity.cpp

Introduce consistent types and parameters in cubeb public API.

---

src/cubeb_mixer.cpp

Address https://bugzilla.mozilla.org/show_bug.cgi?id=1374275#c7

Fix mixer warnings

---

src/cubeb_audiounit.cpp
src/cubeb_mixer.cpp
src/cubeb_pulse.c
src/cubeb_wasapi.cpp
test/test_sanity.cpp

This address #335 .
@ChunMinChang can you please have a look?

Skip mixing when layout is set to undefined

---

src/cubeb_audiounit.cpp

In several places (listeners install/remove etc) we assume that the default device is used. This is correct in many cases but not always. This patch replace the use of the default device with the current device according to the following rules:
* `stream::{in|out}put_device` since the very beginning of stream_init and for the rest of the session contains the current device id. In duplex stream the device id of aggregate device is stored in `stream::aggregate_device_id` and the `stream::{in|out}put_device` contains the selected devices which have been combined to form the AD. 
* when a default device is selected the value of `stream::is_default_{in|out}put` is true
* Install or remove device change listeners will use the current device even in the case of aggregate device.
* Remove …

audiounit: refactor to use device id instead of default device

---

include/cubeb/cubeb.h
src/cubeb_audiotrack.c
src/cubeb_opensl.c
test/test_latency.cpp
test/test_mixer.cpp
test/test_sanity.cpp

See https://github.com/kinetiknz/cubeb/issues/346

Remove unused B2G-only stream_type field from cubeb_stream_params.

---

src/cubeb_pulse.c

pulse: Improve handling when there are no pulse source/sink.

---

src/cubeb_audiounit.cpp

Return cubeb error status from `audiounit_set_device_info` since `audiounit_get_default_device_id` can fail.
Error found in the following crash id:
https://crash-stats.mozilla.com/report/index/920b342c-e152-471d-ae16-fcb800170919

audiounit: expect error when set device info.

---

src/cubeb_audiounit.cpp

Fix for crash in bug 1409216. The active stream counter is advanced right after the allocation of the new cubeb stream.

audiounit: advance active stream counter earlier in stream init (Bug 1409216)

---

CMakeLists.txt

On OS/2, visibility attribute is not supported.

os2: disable visibility attribute

---

src/cubeb_audiounit.cpp

On failed reinit we need to unregister system listeners to avoid unexpected callbacks.

audiounit: unregister system listeners after failed reinit.

---

src/cubeb_resampler.h

Update some comments which appear to have become out of step with their respective code.

Update comments in cubeb-resampler.h

---

src/cubeb_sndio.c

This adds recording and full-duplex support for the sndio backend. Most of the changes prepare the existing code by renaming symbols and by fixing constucts that make difficult implementation of the recording bits.

add support for recording in sndio backend

---

src/cubeb_audiounit.cpp

Limit the effect of workaround only when AirPods are used. If it's not AirPods use the old code path.
cc @djg

audiounit: apply workaround only to AirPods.

---

src/cubeb_jack.cpp

Please find the description in Bug 1422664. The fix is verified by the reporter.

jack: expect null pointer from jack_get_ports (Bug 1422664)

---

src/cubeb_audiounit.cpp

audiounit: guard counter with stream mutex similar to stream init.

---

src/cubeb_mixer.cpp

Don't use popcount intrinsec

---

src/cubeb.c

Remove output channel count limitation.

---

src/cubeb_audiounit.cpp

The presentation latency of a stream is roughly kAudioDevicePropertyLatency +
kAudioStreamPropertyLatency + kAudioUnitProperty_Latency.  Calculate this at
device setup time and apply the correction when calculating the current stream
position for stream_get_position.

audiounit: Apply latency correction to stream_get_position.

---

src/cubeb_wasapi.cpp

See https://bugzilla.mozilla.org/show_bug.cgi?id=1449555#c5 for background.

wasapi: Make CO_E_NOTINITIALIZED a soft error.

---

src/cubeb_audiounit.cpp

Reset string reference before reusing it at the point we read the device information. This is an attempt to fix crash described in BMO 1436713. I am not certain about the root cause of the crash, the conditions that we are crashing are not clear, however it's a change in the right direction.

audiounit: clear reference before re-use it.

---

src/cubeb_audiounit.cpp

If the BT headset is set as default device, it will be opened using the A2DP profile (44.1kHz, 2 channels, 24 bits). As soon as you open the microphone it switches to HFP (output set to 16kHz, mono, 16 bits)...

Fix use of bluetooth headset in handsfree mode on mac

---

src/cubeb_pulse.c

Use separate callback for input and output devices. This will allow to register a context with different notification callbacks for different type of devices.

pulse: separate input output callbacks for collection changes (BMO 1498242)

---

src/cubeb_pulse.c

Some extra logs to help on debugging.

pulse: add some extra logs at stream init/destroy/start/stop

---

CMakeLists.txt
tools/cubeb-test.cpp

Cubeb client for testing. This is pretty simple right now. Hopefully, we will enhance it little by little.

Cubeb app for basic testing.

---

tools/cubeb-test.cpp

Some improvements I made while I was testing device collection changed. It has been enhanced to provide options for starting/stopping a stream, registering a new callback etc.

cubeb-test: improvements for testing collection changed callback

---

tools/cubeb-test.cpp

Add options to change log level on the fly.

cubeb-test: add options to enable/disable logs.

---

src/cubeb_wasapi.cpp

Implement device collection changed callback for wasapi backend. Similar to the other platforms:
* It takes separated callback for input and output device changes.
* if device type is `input | output` the same callback is for input and output changes.
* A second register without an unregister first, for the same device type, creates an assert failure.

wasapi: implement device collection changed callback

---

src/cubeb_audiounit.cpp

Attempt to solve crash in Bug 1541101.

audiounit: replace assert check with error handling. BMO 1541101

---

src/cubeb_audiounit.cpp

minor corrections for typos. r? @achronop  please.

correct typo

---

src/cubeb_audiounit.cpp

In the current code, sometimes we use `0` as `kAudioObjectUnknown`. It would be better if we can replace `0` by `kAudioObjectUnknown`, even the `kAudioObjectUnknown` is actually `0` now.
1. The value of `kAudioObjectUnknown` is defined by the system. We should align it in case `kAudioObjectUnknown` value is changed. 
2. The default values of `plugin_id` and `aggregate_device_id ` are set to `0`, but we have checks for  `plugin_id != kAudioObjectUnknown` or `aggregate_device_id != kAudioDeviceUnknown`(e.g., in `audiounit_destroy_aggregate_device`). It would be more consistent if we initialize them to `kAudioObjectUnknown` instead of `0`.

Replace 0 by kAudioObjectUnknown

---

src/cubeb_opensl.c

Reviewed by @achronop in <https://phabricator.services.mozilla.com/D27572>, as it's still part of my big series there.
This guards improper API usage to only call them, at runtime, during setup, on a device that is recent enough. Effectively, this means this backend works on devices that run API level 16 or more recent. This is Android 4.1.x, codename JellyBean, July 2012 or so.

BMO bug 1531833 - Only call opensl API when supported

---

tools/cubeb-test.cpp

Add an option in the tool to get the position of the stream.

test: add option to get the posotion of a stream

---

test/test_ring_buffer.cpp
tools/cubeb-test.cpp

Just some warnings fix about types and unnecessary lambda captures.

Fix tests warnings

---

tools/cubeb-test.cpp

for testing drain behavior of the stream.

tool: add an option to force stream drain

---

tools/cubeb-test.cpp

Add an option to return the max channel of the output device

tool: get the max number of output channels.

---

src/cubeb_pulse.c

The problem was that after a default device change the cubeb_get_max_channel_count() returned the wrong number of channels; it returned the device info (including channel count) of the initial default device. In order to update the default device info dynamically, a subscription to the  event is created during context initialization and the device info is updated accordingly.

pulse: when default device changes update the info

---

src/cubeb_wasapi.cpp

See https://bugzilla.mozilla.org/show_bug.cgi?id=1583105

wasapi: Address potential UAF in bailout handling.

---

src/cubeb_audiounit.cpp

Import the fix from https://github.com/ChunMinChang/cubeb-coreaudio-rs/commit/4acd80233efa645ac79769f37b07d495c1b42070 that was reviewed in bugzilla. r? @padenot please.

Destroy stream properly

---

include/cubeb/cubeb.h

Updated the docs according to what has been agreed in https://github.com/djg/cubeb-pulse-rs/pull/54

Add in header doc the switching devices behavior.

---

src/cubeb_wasapi.cpp

Reference:
https://docs.microsoft.com/en-us/windows/win32/api/audioclient/nf-audioclient-iaudioclient-isformatsupported

Fixed small memory leak

---

src/cubeb_wasapi.cpp

Two issues, explained with comments in the code.

 Clarify and fix expectations around wasapi_create_device, fix crashes

---

src/cubeb_oss.c

This fixes https://github.com/kinetiknz/cubeb/pull/600#issuecomment-706457745 .

oss: Initialize cubeb_stream::state properly

---

src/cubeb_oss.c

The intent behind this change is that the original code was complex. The original code tried to do its internal buffering in combine with non-blocking I/O, without considering the actual space of buffers on the sound(4)-side. This ended up calling the data callback in a way the not reflecting a supposed timing of audio stream pulling/pushing by hardware/kernel sound layer, and could make it harder for the library client to calculate its own timing.
The new code does away non-blocking I/O and this extra internal audio buffering all together. It directly uses the sound(4)'s buffer status to issue audio stream pulling/pushing call with number of frames matching as much as possible to the audio buffer status reflected by sound(4).
Tested on Firefox 83.0 on FreeBSD 12.2-RELEASE, without …

Rework the buffering logic

---

src/cubeb_aaudio.cpp

On some device (namely, a Samsung Galaxy A30 running Android 10, see
https://bugzilla.mozilla.org/show_bug.cgi?id=1679932), the state is
"STARTED" for quite some time, so we don't go into the `if` statement.
It's best to fallback.
We then need to ensure the monotonicity of this clock (since now we use
two distinct ways of reporting the time, it can end up being
non-monotonic for some calls), using the same technique we use on other
backends.

Fix clock reporting on the AAudio backend

---

src/cubeb_oss.c

As for output-only stream we do not wait on the buffer at all, the CPU usage would spin to 100%.
I would like this PR to be backported to Firefox 85 as well.

oss: Fix CPU spinning 100%

---

src/cubeb_wasapi.cpp

Fix a couple of warnings in cubeb_wasapi.cpp

---

src/cubeb_oss.c

There is a bug in the OSS cubeb code which use the previous number of
frames as input for the next data-exchange, when full-duplex is
activated. This causes noticable jitter, because the wrong number of
audio frames is exchanged.
The solution is to check both input and output audio DSP buffers and
select the minimum number of audio frames which can be transferred when
full duplex is activated.

oss: Use the minimum space of both direction in full-duplex path

---

src/cubeb_wasapi.cpp

Attempt to address [BMO 1624067](https://bugzilla.mozilla.org/show_bug.cgi?id=1624067) by handling volume adjustment internally rather than using IAudioStreamVolume.
If this solves BMO 1624067, I'll remove the CUBEB_WASAPI_USE_IAUDIOSTREAMVOLUME path entirely.

wasapi: Adjust output stream volume internally rather than using IAudioStreamVolume.

---

src/cubeb_sndio.c

cf https://bugzilla.mozilla.org/show_bug.cgi?id=1633769

sndio: default max_channels to 8 for OUTPUT and 2 for INPUT

---

src/cubeb_alsa.c
src/cubeb_jack.cpp

jack: possibility to disable lazy load of lib

---

src/cubeb_oss.c

This patch is proposed by @hselasky to fix an issue that causes corruption when upstream buffer size is larger than our specified buffer size.
The corresponding ticket is https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=260061.

cubeb_oss: Fix for buffer overrun.

---

src/cubeb_mixer.cpp

mixer: Replace std::result_of with decltype.

---

tools/cubeb-test.cpp

It's a lot easier to develop/debug device-related features/issues if we
can select input or/and output device for the audio stream in cubeb-test

Add device selection to cubeb-test

---

src/cubeb_audiounit.cpp
src/cubeb_pulse.c
src/cubeb_wasapi.cpp
test/test_callback_ret.cpp

This is work towards solving https://github.com/mozilla/cubeb/issues/553

Clean up `data_callback` error handling

---

src/cubeb_wasapi.cpp

- Rather than "leak" an atomic bool to the stuck render thread, we
instead "leak" the entire stream and leave the render thread to clean
up.
- Render thread now checks `handle_emergency_bailout()`, which frees the
stream and exits the render thread in bailout condititions.
- Removed `thread_ready_event`, since it's no longer needed.

wasapi: Rework emergency_bailout mechanism.

---

src/cubeb_aaudio.cpp
src/cubeb_alsa.c
src/cubeb_jack.cpp
src/cubeb_pulse.c
src/cubeb_sndio.c

Add #ifndef around dlclose() to allow build with "LAZY_LOAD_LIBS=OFF"  cmake argument.

Fix build with "LAZY_LOAD_LIBS=OFF".

---

src/cubeb_wasapi.cpp

Fix warnings in cubeb_wasapi.cpp.

---

src/cubeb_sndio.c

cf https://bugzilla.mozilla.org/show_bug.cgi?id=1814359

sndio: switch audio to 24-bit precision

---

src/cubeb_wasapi.cpp

This is intended to fix [BMO 1838241](https://bugzilla.mozilla.org/show_bug.cgi?id=1838241).  Since https://github.com/mozilla/cubeb/commit/febf49d0898d1c1691235639b0796b91df522394 was merged, the render thread exists for the lifetime of the stream (rather than just the duration between a stream start and stop) - this results in the render thread handling reconfigure events for inactive (stopped) streams, which is not necessary as stream start will handle reconfiguration if the audio device was lost while the stream was stopped.
Moving the acquisition of the stream_reset_lock in 4c6c317a37d1ef6034b3ca117bffa0906650eb1b should be sufficient to avoid the race/crash seen in BMO 1838241. d1e46c727e5284c71880657f493c7580d9cd86ea adds an `active` flag to the stream and uses that to ignore …

wasapi: Avoid reconfiguring inactive streams

---

src/cubeb_opensl.cpp

https://bugzilla.mozilla.org/show_bug.cgi?id=1860423

Return an error if failing to open a recorder and it's not a sample-rate not supported issue

---

src/cubeb_jack.cpp

Fixes https://github.com/mozilla/cubeb/issues/774

Checking buffer, buffer_in, buffer_out pointers for non NULL values

---

src/cubeb.c

e.g. https://www.audiophonics.fr/fr/dac-avec-volume/topping-e30-dac-ak4493-usb-32bit768khz-dsd512-xmos-noir-p-14486.html

Some DACs can go up to 768kHz

---

src/cubeb_aaudio.cpp

See individual commits for details.

Adjust AAudio buffer sizes and fix high latency draining

---

.github/workflows/docs.yml
README.md
include/cubeb/cubeb.h

It deserves at least a nice readme I think.

Improve readme, fix docs, publish them

---

CMakeLists.txt
include/cubeb/cubeb.h
scripts/run-clang-format.sh
src/cubeb_wasapi.cpp

Related:
- https://github.com/mozilla/cubeb-pulse-rs/pull/98
- https://github.com/mozilla/cubeb-coreaudio-rs/pull/254

 Call the device collection change callback when the default device changes 

---

include/cubeb/cubeb.h
src/cubeb_aaudio.cpp
test/test_latency.cpp
tools/cubeb-test.cpp

This is intended to address [BMO 1983881](https://bugzilla.mozilla.org/show_bug.cgi?id=1983881).

aaudio: Ensure ERROR state updates are reported correctly.
